// frontend/src/pages/overview/seed-analysis-panel.tsx
/**
 * SeedAnalysisPanel — shows seed analysis results (characters, organizations, relations).
 */

import { useCallback, useState } from "react";
import { Loader2 } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { runSeedAnalysis } from "@/api/novel";
import type { Project } from "@/types/project";
import { resolveSeedProjectId } from "./seed-project-id";

/* ---------- Display helpers ---------- */

const IMPORTANCE_TIER_TEXT: Record<string, string> = {
  protagonist: "主角",
  major: "重要角色",
  supporting: "配角",
  minor: "次要角色",
};

const ORG_TYPE_TEXT: Record<string, string> = {
  organization: "组织",
  org: "组织",
  group: "团体",
  faction: "势力",
  guild: "公会",
  sect: "宗门",
  school: "学派",
  company: "公司",
};

function formatImportanceTier(value: string | undefined): string {
  if (!value) return "-";
  return IMPORTANCE_TIER_TEXT[value] || value;
}

function formatOrganizationType(value: string | undefined): string {
  if (!value) return "-";
  return ORG_TYPE_TEXT[value] || value;
}

/* ---------- Types ---------- */

interface SeedCharacter {
  name: string;
  importance_tier?: string;
  personality_traits?: string[];
  speech_style?: string;
}

interface SeedOrganization {
  name: string;
  organization_type?: string;
}

interface SeedResult {
  characters?: SeedCharacter[];
  organizations?: SeedOrganization[];
  relations?: unknown[];
}

/* ---------- Props ---------- */

interface SeedAnalysisPanelProps {
  projects: Project[];
  projectId: string;
}

/* ---------- Component ---------- */

export default function SeedAnalysisPanel({
  projects,
  projectId,
}: SeedAnalysisPanelProps) {
  const [seedProjectId, setSeedProjectId] = useState(projectId);
  const [seedResult, setSeedResult] = useState<SeedResult | null>(null);
  const [seedError, setSeedError] = useState("");
  const [seedBusy, setSeedBusy] = useState(false);

  const characterCount = seedResult?.characters?.length || 0;
  const organizationCount = seedResult?.organizations?.length || 0;
  const relationCount = seedResult?.relations?.length || 0;
  const charactersPreview = (seedResult?.characters || []).slice(0, 6);
  const organizationsPreview = (seedResult?.organizations || []).slice(0, 6);

  const analyzeSeed = useCallback(
    async (projectIdOverride = "") => {
      try {
        setSeedBusy(true);
        setSeedError("");
        const targetProjectId = resolveSeedProjectId(
          projectIdOverride,
          seedProjectId,
        );
        if (!targetProjectId) {
          setSeedError("缺少项目 ID");
          return;
        }
        const response = await runSeedAnalysis({
          projectId: targetProjectId,
          graphId: "",
          analysisGoal: "",
        });
        setSeedResult((response.data as SeedResult) || null);
      } catch (err) {
        setSeedError(
          err instanceof Error ? err.message : "种子分析请求失败",
        );
        setSeedResult(null);
      } finally {
        setSeedBusy(false);
      }
    },
    [seedProjectId],
  );

  return (
    <Card>
      <CardContent className="p-3 space-y-3">
        <h2 className="font-serif text-lg font-bold">分析结果</h2>
        <p className="text-sm text-muted-foreground">
          查看角色、组织、关系的分析结果。
        </p>

        <div>
          <Button
            size="sm"
            disabled={seedBusy || !seedProjectId}
            onClick={() => analyzeSeed()}
          >
            {seedBusy ? (
              <>
                <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
                分析中...
              </>
            ) : (
              "运行分析"
            )}
          </Button>
        </div>

        {/* KPIs */}
        {seedResult && (
          <div className="grid grid-cols-3 gap-1.5 mt-3">
            <div className="rounded-lg border bg-amber-50/60 p-2 flex flex-col gap-1.5">
              <span className="font-mono text-xs text-muted-foreground">角色</span>
              <strong className="text-base">{characterCount}</strong>
            </div>
            <div className="rounded-lg border bg-amber-50/60 p-2 flex flex-col gap-1.5">
              <span className="font-mono text-xs text-muted-foreground">组织</span>
              <strong className="text-base">{organizationCount}</strong>
            </div>
            <div className="rounded-lg border bg-amber-50/60 p-2 flex flex-col gap-1.5">
              <span className="font-mono text-xs text-muted-foreground">关系</span>
              <strong className="text-base">{relationCount}</strong>
            </div>
          </div>
        )}

        {/* Lists */}
        {seedResult && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5 mt-3">
            {/* Characters */}
            <div className="rounded-lg border bg-amber-50/30 p-2.5">
              <div className="font-bold text-sm mb-1.5">角色列表（预览）</div>
              {charactersPreview.map((item) => (
                <div
                  key={item.name}
                  className="border-t border-dashed py-2 flex flex-col first:border-t-0"
                >
                  <div className="flex items-center justify-between gap-2">
                    <strong className="text-sm">{item.name}</strong>
                    <span className="font-mono text-xs text-muted-foreground">
                      {formatImportanceTier(item.importance_tier)}
                    </span>
                  </div>
                  {(item.personality_traits?.length || item.speech_style) && (
                    <div className="mt-1 flex flex-wrap items-center gap-1">
                      {item.personality_traits?.slice(0, 3).map((trait) => (
                        <Badge
                          key={trait}
                          variant="secondary"
                          className="text-[11px]"
                        >
                          {trait}
                        </Badge>
                      ))}
                      {item.speech_style && (
                        <span className="text-[11px] text-muted-foreground italic">
                          {item.speech_style}
                        </span>
                      )}
                    </div>
                  )}
                </div>
              ))}
            </div>

            {/* Organizations */}
            <div className="rounded-lg border bg-amber-50/30 p-2.5">
              <div className="font-bold text-sm mb-1.5">组织列表（预览）</div>
              {organizationsPreview.map((item) => (
                <div
                  key={item.name}
                  className="border-t border-dashed py-2 flex items-center justify-between first:border-t-0"
                >
                  <strong className="text-sm">{item.name}</strong>
                  <span className="font-mono text-xs text-muted-foreground">
                    {formatOrganizationType(item.organization_type)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Error */}
        {seedError && (
          <p className="mt-2 text-sm text-destructive">{seedError}</p>
        )}
      </CardContent>
    </Card>
  );
}

// frontend/src/views/overview/SeedAnalysisPanel.vue
<template>
  <article class="workbench-card panel seed-panel">
    <h2 class="card-title">分析结果</h2>
    <p>查看角色、组织、关系的分析结果。</p>
    <div class="toolbar-row">
      <button class="btn primary" :disabled="seedBusy || !seedProjectId" @click="analyzeSeed()">
        {{ seedBusy ? "分析中..." : "运行分析" }}
      </button>
    </div>

    <div class="kpis seed-kpis" v-if="seedResult">
      <div class="kpi"><span class="mono">角色</span><strong>{{ seedCharacterCount }}</strong></div>
      <div class="kpi"><span class="mono">组织</span><strong>{{ seedOrganizationCount }}</strong></div>
      <div class="kpi"><span class="mono">关系</span><strong>{{ seedRelationCount }}</strong></div>
    </div>

    <div class="seed-lists" v-if="seedResult">
      <div class="seed-col">
        <div class="seed-title">角色列表（预览）</div>
        <div class="seed-item" v-for="item in seedCharactersPreview" :key="item.name">
          <div class="seed-item-main">
            <strong>{{ item.name }}</strong>
            <span class="mono">{{ formatImportanceTier(item.importance_tier) }}</span>
          </div>
          <div class="seed-item-detail" v-if="item.personality_traits?.length || item.speech_style">
            <span v-if="item.personality_traits?.length" class="trait-chips">
              <span class="trait-chip" v-for="trait in item.personality_traits.slice(0, 3)" :key="trait">{{ trait }}</span>
            </span>
            <span v-if="item.speech_style" class="speech-hint">{{ item.speech_style }}</span>
          </div>
        </div>
      </div>
      <div class="seed-col">
        <div class="seed-title">组织列表（预览）</div>
        <div class="seed-item" v-for="item in seedOrganizationsPreview" :key="item.name">
          <strong>{{ item.name }}</strong>
          <span class="mono">{{ formatOrganizationType(item.organization_type) }}</span>
        </div>
      </div>
    </div>

    <p class="seed-error" v-if="seedError">{{ seedError }}</p>
  </article>
</template>

<script setup>
import { computed, ref, watch } from "vue";

import { runSeedAnalysis } from "../../api/novel";
import {
  resolveSeedProjectId,
} from "./seedProjectId";
import {
  formatImportanceTier,
  formatOrganizationType,
} from "../../utils/chineseDisplay";

const props = defineProps({
  projects: { type: Array, default: () => [] },
  projectId: { type: String, default: "" },
});

const seedProjectId = ref(props.projectId);
const seedResult = ref(null);
const seedError = ref("");
const seedBusy = ref(false);
const seedCharacterCount = computed(() => seedResult.value?.characters?.length || 0);
const seedOrganizationCount = computed(() => seedResult.value?.organizations?.length || 0);
const seedRelationCount = computed(() => seedResult.value?.relations?.length || 0);
const seedCharactersPreview = computed(() => (seedResult.value?.characters || []).slice(0, 6));
const seedOrganizationsPreview = computed(() => (seedResult.value?.organizations || []).slice(0, 6));

async function analyzeSeed(projectIdOverride = "") {
  try {
    seedBusy.value = true;
    seedError.value = "";
    const targetProjectId = resolveSeedProjectId(projectIdOverride, seedProjectId.value);
    const response = await runSeedAnalysis({
      projectId: targetProjectId,
    });
    seedResult.value = response.data || null;
  } catch (error) {
    seedError.value = error.message || "种子分析请求失败";
    seedResult.value = null;
  } finally {
    seedBusy.value = false;
  }
}

async function runForProject(projectId) {
  seedProjectId.value = projectId;
  await analyzeSeed(projectId);
}

watch(
  () => props.projectId,
  (value) => {
    if (value && value !== seedProjectId.value) {
      seedProjectId.value = value;
      seedResult.value = null;
      seedError.value = "";
    }
  },
);

defineExpose({ runForProject });
</script>

<style scoped>
.panel {
  padding: 18px;
}

.panel p {
  margin: 8px 0 0;
  color: var(--text-sub);
}

.seed-panel {
  grid-column: 1 / -1;
}

.kpis {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 8px;
  margin-top: 14px;
}

.kpi {
  border: 1px solid var(--line-soft);
  border-radius: 12px;
  background: #fffbf0;
  padding: 10px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.kpi span {
  color: var(--text-sub);
  font-size: 12px;
}

.kpi strong {
  font-size: 16px;
}

.seed-kpis {
  margin-top: 12px;
}

.seed-lists {
  margin-top: 12px;
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: 10px;
}

.seed-col {
  border: 1px solid var(--line-soft);
  border-radius: 12px;
  background: #fffaf0;
  padding: 10px;
}

.seed-title {
  font-weight: 700;
  margin-bottom: 6px;
}

.seed-item {
  border-top: 1px dashed var(--line-soft);
  padding: 7px 0;
  display: flex;
  flex-direction: column;
}

.seed-item-main {
  display: flex;
  justify-content: space-between;
  gap: 10px;
}

.seed-item-detail {
  margin-top: 4px;
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
  align-items: center;
}

.trait-chips {
  display: flex;
  gap: 3px;
}

.trait-chip {
  background: rgba(176, 125, 75, 0.1);
  border-radius: 4px;
  padding: 1px 6px;
  font-size: 11px;
  color: var(--accent-copper-deep);
}

.speech-hint {
  font-size: 11px;
  color: var(--text-dim);
  font-style: italic;
}

.seed-item:first-of-type {
  border-top: none;
}

.seed-error {
  margin-top: 10px;
  color: #9b4326;
}

@media (max-width: 980px) {
  .seed-lists {
    grid-template-columns: 1fr;
  }
}
</style>
