// frontend/src/pages/writer/scene-list-panel.tsx
/**
 * SceneListPanel — list of scenes for the current chapter.
 * Supports selection, add, and delete.
 */

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Plus, X } from "lucide-react";
import type { SceneItem } from "./use-writer-state";

interface SceneListPanelProps {
  scenes: SceneItem[];
  selectedSceneId: string;
  onSelect: (sceneId: string) => void;
  onAdd: () => void;
  onDelete: (sceneId: string) => void;
}

const STATUS_LABELS: Record<string, string> = {
  draft: "草稿",
  review: "审阅中",
  final: "定稿",
};

const STATUS_VARIANTS: Record<string, "default" | "secondary" | "destructive" | "outline"> = {
  draft: "secondary",
  review: "default",
  final: "default",
};

export function SceneListPanel({
  scenes,
  selectedSceneId,
  onSelect,
  onAdd,
  onDelete,
}: SceneListPanelProps) {
  return (
    <div className="mt-3 flex flex-col border-t border-border/40 pt-2">
      <div className="flex items-center justify-between px-1 pb-2">
        <span className="text-sm font-semibold">场景列表</span>
        <Button variant="ghost" size="icon" className="h-6 w-6" onClick={onAdd} title="添加场景">
          <Plus className="h-4 w-4" />
        </Button>
      </div>
      <div className="flex flex-1 flex-col gap-1.5 overflow-y-auto">
        {scenes.map((scene) => (
          <div
            key={scene.scene_id}
            className={`group relative cursor-pointer rounded-md border px-3 py-2 text-sm transition-colors ${
              scene.scene_id === selectedSceneId
                ? "border-primary/40 bg-primary/5"
                : "border-border/40 bg-card hover:border-muted-foreground/30"
            }`}
            onClick={() => onSelect(scene.scene_id)}
          >
            <div className="mb-1 flex items-center justify-between">
              <span className="text-xs text-muted-foreground font-semibold">
                {scene.scene_order}
              </span>
              <Badge variant={STATUS_VARIANTS[scene.status] || "outline"} className="text-[10px]">
                {STATUS_LABELS[scene.status] || scene.status}
              </Badge>
            </div>
            <div className="truncate text-[13px] font-medium">
              {scene.title || `场景 ${scene.scene_order}`}
            </div>
            <div className="text-[11px] text-muted-foreground">
              {scene.word_count || 0} 字
            </div>
            <Button
              variant="ghost"
              size="icon"
              className="absolute right-1.5 top-1.5 hidden h-5 w-5 group-hover:flex"
              onClick={(e) => {
                e.stopPropagation();
                onDelete(scene.scene_id);
              }}
              title="删除"
            >
              <X className="h-3.5 w-3.5" />
            </Button>
          </div>
        ))}
        {scenes.length === 0 && (
          <div className="py-10 text-center text-xs text-muted-foreground">
            暂无场景，点击 + 添加
          </div>
        )}
      </div>
    </div>
  );
}

// frontend/src/views/writer/SceneListPanel.vue
<template>
  <div class="scene-list-panel">
    <div class="scene-list-header">
      <span class="scene-list-title">场景列表</span>
      <n-button size="tiny" quaternary @click="$emit('add')" title="添加场景"><Icon icon="icon-park-outline:plus" width="16" /></n-button>
    </div>
    <div class="scene-list-body">
      <div
        v-for="scene in scenes"
        :key="scene.scene_id"
        :class="['scene-item', { 'scene-item--active': scene.scene_id === selectedSceneId }]"
        @click="$emit('select', scene.scene_id)"
      >
        <div class="scene-item-header">
          <span class="scene-order">{{ scene.scene_order }}</span>
          <n-tag :type="statusType(scene.status)" size="small">{{ statusLabel(scene.status) }}</n-tag>
        </div>
        <div class="scene-item-title">{{ scene.title || `场景 ${scene.scene_order}` }}</div>
        <div class="scene-item-meta">{{ scene.word_count || 0 }} 字</div>
        <n-button
          class="scene-delete-btn"
          size="tiny"
          quaternary
          @click.stop="$emit('delete', scene.scene_id)"
          title="删除"
        ><Icon icon="icon-park-outline:close-small" width="14" /></n-button>
      </div>
      <div v-if="!scenes.length" class="scene-list-empty">
        暂无场景，点击 + 添加
      </div>
    </div>
  </div>
</template>

<script setup>
import { NButton, NTag } from "naive-ui";
import { Icon } from "@iconify/vue";

defineProps({
  scenes: { type: Array, default: () => [] },
  selectedSceneId: { type: String, default: "" },
});

defineEmits(["select", "add", "delete"]);

function statusLabel(status) {
  const map = { draft: "草稿", review: "审阅中", final: "定稿" };
  return map[status] || status;
}

function statusType(status) {
  const map = { draft: "warning", review: "info", final: "success" };
  return map[status] || "default";
}
</script>

<style scoped>
.scene-list-panel {
  display: flex;
  flex-direction: column;
  height: 100%;
  border-right: 1px solid #e0e0e0;
  background: #fafafa;
}
.scene-list-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  border-bottom: 1px solid #e0e0e0;
  font-weight: 600;
}
.scene-list-body {
  flex: 1;
  overflow-y: auto;
  padding: 8px;
}
.scene-item {
  position: relative;
  padding: 10px 12px;
  margin-bottom: 6px;
  border-radius: 6px;
  cursor: pointer;
  background: #fff;
  border: 1px solid #eee;
  transition: all 0.15s;
}
.scene-item:hover { border-color: #aaa; }
.scene-item--active {
  border-color: #409eff;
  background: #ecf5ff;
}
.scene-item-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 4px;
}
.scene-order {
  font-size: 12px;
  color: #999;
  font-weight: 600;
}
.scene-item-title {
  font-size: 13px;
  color: #333;
  margin-bottom: 4px;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}
.scene-item-meta {
  font-size: 11px;
  color: #aaa;
}
.scene-delete-btn {
  position: absolute;
  top: 8px;
  right: 8px;
  display: none;
}
.scene-item:hover .scene-delete-btn { display: block; }
.scene-list-empty {
  text-align: center;
  color: #ccc;
  padding: 40px 0;
  font-size: 13px;
}
</style>
