// frontend/src/views/writer/ManuscriptReadingPane.vue
<template>
  <div class="reading-pane">
    <div class="reading-header">
      <h2 class="reading-chapter-title">{{ chapterTitle }}</h2>
      <div class="reading-stats">{{ totalWords }} 字 · {{ blocks.length }} 段</div>
    </div>
    <div class="reading-scroll">
      <template v-if="blocks.length">
        <div
          v-for="block in blocks"
          :key="block.block_id"
          class="prose-block"
          :class="{ 'prose-block--editing': editingId === block.block_id }"
          @mouseenter="hoveredId = block.block_id"
          @mouseleave="hoveredId = null"
        >
          <!-- Floating action bar on hover -->
          <div
            v-if="hoveredId === block.block_id && editingId !== block.block_id"
            class="block-hover-actions"
          >
            <span class="block-order-hint">#{{ block.block_order }}</span>
            <button class="hover-btn" @click="startEdit(block.block_id)">编辑</button>
            <button class="hover-btn hover-btn--danger" @click="$emit('delete', block.block_id)">删除</button>
          </div>

          <!-- Edit mode -->
          <textarea
            v-if="editingId === block.block_id"
            ref="editorRef"
            class="prose-editor"
            :value="block.content"
            @input="e => $emit('edit-input', block, e.target.value)"
          ></textarea>
          <div v-if="editingId === block.block_id" class="prose-editor-bar">
            <span class="editor-hint">{{ block.word_count }} 字</span>
            <button class="hover-btn" @click="editingId = null">完成</button>
          </div>

          <!-- Read mode -->
          <div v-else class="prose-text">{{ block.content }}</div>
        </div>
      </template>
      <div v-else class="reading-empty">尚无稿件内容</div>
    </div>
  </div>
</template>

<script setup>
import { ref } from "vue";

defineProps({
  blocks: { type: Array, default: () => [] },
  chapterTitle: { type: String, default: "" },
  totalWords: { type: Number, default: 0 },
});

defineEmits(["delete", "edit-input"]);

const hoveredId = ref(null);
const editingId = ref(null);

function startEdit(blockId) {
  editingId.value = blockId;
}

defineExpose({ editingId });
</script>

<style scoped>
.reading-pane {
  display: flex;
  flex-direction: column;
  min-height: 0;
  overflow: hidden;
}

.reading-header {
  padding: 14px 20px 10px;
  border-bottom: 1px solid var(--border-subtle, #2d2d44);
}

.reading-chapter-title {
  font-size: 16px;
  font-weight: 700;
  color: var(--text-primary, #e0e0e0);
  margin: 0;
}

.reading-stats {
  font-size: 12px;
  color: var(--text-tertiary, #888);
  margin-top: 4px;
}

.reading-scroll {
  flex: 1;
  overflow-y: auto;
  padding: 16px 20px 24px;
}

.prose-block {
  position: relative;
  padding: 2px 0 12px;
  border-bottom: 1px dashed transparent;
  transition: border-color 0.2s;
}

.prose-block:hover {
  border-bottom-color: var(--border-subtle, #2d2d44);
}

.prose-block + .prose-block {
  margin-top: 8px;
}

.prose-block--editing {
  border-bottom-color: var(--border-active, #4060c0);
}

.prose-text {
  font-size: 15px;
  line-height: 1.9;
  color: var(--text-primary, #e0e0e0);
  white-space: pre-wrap;
  font-family: "Noto Serif SC", "Source Han Serif CN", serif, inherit;
}

.block-hover-actions {
  position: absolute;
  top: 0;
  right: 0;
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 2px 6px;
  background: var(--surface-tertiary, #252540);
  border: 1px solid var(--border-subtle, #2d2d44);
  border-radius: 4px;
  z-index: 2;
}

.block-order-hint {
  font-size: 10px;
  color: var(--text-tertiary, #888);
  margin-right: 4px;
}

.hover-btn {
  background: none;
  border: none;
  font-size: 11px;
  color: var(--text-secondary, #aaa);
  cursor: pointer;
  padding: 2px 6px;
  border-radius: 3px;
}
.hover-btn:hover {
  background: var(--surface-hover, #303050);
  color: var(--text-primary, #e0e0e0);
}
.hover-btn--danger { color: #e05050; }
.hover-btn--danger:hover { color: #ff6060; background: rgba(224, 80, 80, 0.1); }

.prose-editor {
  width: 100%;
  min-height: 160px;
  background: var(--surface-tertiary, #252540);
  border: 1px solid var(--border-active, #4060c0);
  border-radius: 6px;
  padding: 12px 16px;
  font-size: 15px;
  line-height: 1.9;
  color: var(--text-primary, #e0e0e0);
  resize: vertical;
  font-family: inherit;
}

.prose-editor-bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  margin-top: 6px;
}

.editor-hint {
  font-size: 11px;
  color: var(--text-tertiary, #888);
}

.reading-empty {
  text-align: center;
  color: var(--text-tertiary, #888);
  padding: 80px 0;
  font-size: 14px;
}
</style>

// frontend/src/pages/writer/manuscript-reading-pane.tsx
/**
 * ManuscriptReadingPane — read-only manuscript view for the drawer.
 */

import * as React from "react";
import type { ManuscriptBlockItem } from "./use-writer-state";

interface ManuscriptReadingPaneProps {
  blocks: ManuscriptBlockItem[];
  chapterTitle: string;
  totalWords: number;
  onDelete: (blockId: string) => void;
  onEditInput: (block: ManuscriptBlockItem, value: string) => void;
}

export function ManuscriptReadingPane({
  blocks,
  chapterTitle,
  totalWords,
  onDelete,
  onEditInput,
}: ManuscriptReadingPaneProps) {
  const [hoveredId, setHoveredId] = React.useState<string | null>(null);
  const [editingId, setEditingId] = React.useState<string | null>(null);

  return (
    <div className="flex min-h-0 flex-col overflow-hidden">
      <div className="border-b border-border/40 px-5 pb-2.5 pt-3.5">
        <h2 className="m-0 text-base font-bold">{chapterTitle}</h2>
        <div className="mt-1 text-xs text-muted-foreground">
          {totalWords} 字 &middot; {blocks.length} 段
        </div>
      </div>
      <div className="flex-1 overflow-y-auto px-5 pb-6 pt-4">
        {blocks.length > 0 ? (
          blocks.map((block) => (
            <div
              key={block.block_id}
              className={`relative border-b border-dashed border-transparent pb-3 pt-0.5 transition-colors hover:border-border/40 ${
                editingId === block.block_id ? "border-primary/30" : ""
              }`}
              onMouseEnter={() => setHoveredId(block.block_id)}
              onMouseLeave={() => setHoveredId(null)}
            >
              {hoveredId === block.block_id && editingId !== block.block_id && (
                <div className="absolute right-0 top-0 z-10 flex items-center gap-1.5 rounded border border-border/40 bg-card px-1.5 py-0.5 text-xs">
                  <span className="text-[10px] text-muted-foreground">
                    #{block.block_order}
                  </span>
                  <button
                    type="button"
                    className="rounded px-1.5 py-0.5 text-muted-foreground transition-colors hover:bg-muted"
                    onClick={() => setEditingId(block.block_id)}
                  >
                    编辑
                  </button>
                  <button
                    type="button"
                    className="rounded px-1.5 py-0.5 text-destructive transition-colors hover:bg-destructive/10"
                    onClick={() => onDelete(block.block_id)}
                  >
                    删除
                  </button>
                </div>
              )}

              {editingId === block.block_id ? (
                <>
                  <textarea
                    className="w-full min-h-[160px] resize-y rounded-md border border-primary bg-muted/30 p-3 font-serif text-[15px] leading-relaxed outline-none"
                    defaultValue={block.content}
                    onChange={(e) => onEditInput(block, e.target.value)}
                  />
                  <div className="mt-1.5 flex items-center justify-between">
                    <span className="text-[11px] text-muted-foreground">
                      {block.word_count} 字
                    </span>
                    <button
                      type="button"
                      className="rounded px-2 py-0.5 text-xs text-muted-foreground transition-colors hover:bg-muted"
                      onClick={() => setEditingId(null)}
                    >
                      完成
                    </button>
                  </div>
                </>
              ) : (
                <div className="whitespace-pre-wrap font-serif text-[15px] leading-relaxed">
                  {block.content}
                </div>
              )}
            </div>
          ))
        ) : (
          <div className="py-20 text-center text-sm text-muted-foreground">
            尚无稿件内容
          </div>
        )}
      </div>
    </div>
  );
}
