// frontend/src/views/writer/ManuscriptTocPanel.vue
<template>
  <div class="ms-toc">
    <div class="toc-header">
      <button class="toc-back-btn" @click="$emit('back')" title="返回写作模式"><span class="toc-back-chevron"></span></button>
      <div>
        <p class="panel-kicker mono">MANUSCRIPT</p>
        <h2 class="panel-title title-ancient">稿件目录</h2>
      </div>
    </div>

    <div class="toc-list">
      <!-- "All" entry -->
      <div
        class="toc-entry"
        :class="{ active: !selectedChapterId }"
        @click="$emit('jump', null)"
      >
        <span class="toc-label">全部</span>
        <span class="toc-meta">{{ totalBlocks }} 段</span>
      </div>

      <!-- Chapter folders -->
      <div v-for="ch in chapters" :key="ch.chapter_id" class="toc-chapter">
        <div
          class="toc-entry toc-entry--chapter"
          :class="{ active: selectedChapterId === ch.chapter_id }"
          @click="handleChapterClick(ch)"
        >
          <!-- Expand/collapse toggle -->
          <button class="toc-toggle-btn" @click.stop="toggleExpand(ch.chapter_id)">
            <span class="toc-toggle-icon" :class="{ expanded: expandedChapters.has(ch.chapter_id) }">▸</span>
          </button>

          <template v-if="renamingId === ch.chapter_id">
            <n-input
              ref="renameInput"
              v-model:value="renameValue"
              size="small"
              @keydown.enter="commitRename(ch.chapter_id)"
              @keydown.escape="cancelRename"
              @blur="commitRename(ch.chapter_id)"
              @click.stop
              style="flex: 1"
            />
          </template>
          <template v-else>
            <span class="toc-label toc-label--chapter">{{ ch.title || '未命名章节' }}</span>
            <span class="toc-meta">{{ ch.blockCount }} 段 · {{ ch.wordCount }} 字</span>
            <div class="toc-actions" @click.stop>
              <button class="toc-action-btn" @click="startRename(ch)" title="重命名">✎</button>
              <button class="toc-action-btn toc-action-btn--danger" @click="$emit('delete-chapter', ch.chapter_id)" title="删除章节">✕</button>
            </div>
          </template>
        </div>

        <!-- Child blocks (expanded) -->
        <div v-if="expandedChapters.has(ch.chapter_id)" class="toc-children">
          <div
            v-for="block in getBlocksForChapter(ch.chapter_id)"
            :key="block.block_id"
            class="toc-entry toc-entry--block"
            @click.stop="$emit('jump', ch.chapter_id)"
          >
            <span class="toc-block-label">{{ blockLabel(block) }}</span>
            <div class="toc-block-actions" @click.stop>
              <n-select
                size="tiny"
                :value="ch.chapter_id"
                :options="moveTargetOptions"
                :consistent-menu-width="false"
                @update:value="val => handleMoveBlock(block.block_id, val, ch.chapter_id)"
                style="width: 90px"
              />
            </div>
          </div>
          <div v-if="getBlocksForChapter(ch.chapter_id).length === 0" class="toc-empty-hint">
            暂无段落
          </div>
        </div>
      </div>

      <!-- Untagged section -->
      <div v-if="untaggedCount > 0" class="toc-chapter">
        <div
          class="toc-entry toc-entry--chapter toc-entry--muted"
          :class="{ active: selectedChapterId === '__untagged__' }"
          @click="$emit('jump', '__untagged__')"
        >
          <button class="toc-toggle-btn" @click.stop="toggleExpand('__untagged__')">
            <span class="toc-toggle-icon" :class="{ expanded: expandedChapters.has('__untagged__') }">▸</span>
          </button>
          <span class="toc-label">未归类</span>
          <span class="toc-meta">{{ untaggedCount }} 段</span>
        </div>

        <div v-if="expandedChapters.has('__untagged__')" class="toc-children">
          <div
            v-for="block in untaggedBlocks"
            :key="block.block_id"
            class="toc-entry toc-entry--block"
          >
            <span class="toc-block-label">{{ blockLabel(block) }}</span>
            <div class="toc-block-actions" @click.stop>
              <n-select
                size="tiny"
                value="__unassign__"
                :options="moveTargetOptions"
                :consistent-menu-width="false"
                @update:value="val => handleMoveBlock(block.block_id, val, '__unassign__')"
                style="width: 90px"
              />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- New chapter -->
    <div class="toc-new">
      <n-input
        v-model:value="newChapterName"
        placeholder="新章节名称..."
        size="small"
        @keydown.enter="handleCreate"
      >
        <template #suffix>
          <n-button text type="primary" size="tiny" :disabled="!newChapterName.trim()" @click.stop="handleCreate">
            添加
          </n-button>
        </template>
      </n-input>
    </div>

    <!-- Stats -->
    <div class="toc-stats-bar">
      <span class="toc-stat-pill">{{ totalWords }} <small>字</small></span>
      <span class="toc-stat-pill">{{ chapters.length }} <small>章</small></span>
      <span class="toc-stat-pill">{{ totalBlocks }} <small>段</small></span>
    </div>

    <!-- Export -->
    <div class="toc-actions-bar">
      <n-button size="small" @click="$emit('export', 'txt')">导出 TXT</n-button>
      <n-button size="small" @click="$emit('export', 'md')">导出 MD</n-button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, nextTick, reactive } from "vue";
import { NButton, NInput, NSelect } from "naive-ui";

const props = defineProps({
  chapters: { type: Array, default: () => [] },
  blocks: { type: Array, default: () => [] },
  selectedChapterId: { type: [String, null], default: null },
  totalWords: { type: Number, default: 0 },
  totalBlocks: { type: Number, default: 0 },
  untaggedCount: { type: Number, default: 0 },
});

const emit = defineEmits([
  "jump", "create-chapter", "rename-chapter", "delete-chapter",
  "move-block", "export", "back",
]);

const newChapterName = ref("");
const renamingId = ref(null);
const renameValue = ref("");
const renameInput = ref(null);
const expandedChapters = reactive(new Set());

const untaggedBlocks = computed(() =>
  props.blocks.filter(b => !b.chapter_id)
);

const moveTargetOptions = computed(() => [
  ...props.chapters.map(c => ({ label: c.title || '未命名', value: c.chapter_id })),
  { label: '未归类', value: '__unassign__' },
]);

function getBlocksForChapter(chapterId) {
  return props.blocks.filter(b => b.chapter_id === chapterId);
}

function blockLabel(block) {
  if (block.summary) return block.summary.slice(0, 40) + (block.summary.length > 40 ? "…" : "");
  if (block.content) return block.content.slice(0, 40) + (block.content.length > 40 ? "…" : "");
  return `段落 #${block.block_order}`;
}

function handleChapterClick(ch) {
  emit("jump", ch.chapter_id);
}

function toggleExpand(id) {
  if (expandedChapters.has(id)) {
    expandedChapters.delete(id);
  } else {
    expandedChapters.add(id);
  }
}

function handleCreate() {
  const name = newChapterName.value.trim();
  if (!name) return;
  emit("create-chapter", name);
  newChapterName.value = "";
}

function startRename(ch) {
  renamingId.value = ch.chapter_id;
  renameValue.value = ch.title || "";
  nextTick(() => {
    const el = renameInput.value;
    const comp = Array.isArray(el) ? el[0] : el;
    if (comp) {
      comp.focus();
      // n-input exposes select() on its internal input
      comp.inputElRef?.select?.();
    }
  });
}

function commitRename(chapterId) {
  const newTitle = renameValue.value.trim();
  if (newTitle) {
    emit("rename-chapter", chapterId, newTitle);
  }
  renamingId.value = null;
}

function cancelRename() {
  renamingId.value = null;
}

function handleMoveBlock(blockId, targetValue, currentValue) {
  if (targetValue === currentValue) return;
  const targetChapterId = targetValue === "__unassign__" ? null : targetValue;
  emit("move-block", blockId, targetChapterId);
}
</script>

<style scoped>
.ms-toc {
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  height: 100%;
  overflow: hidden;
}

.toc-header {
  display: flex;
  align-items: center;
  gap: 10px;
}

.toc-back-btn {
  width: 28px;
  height: 28px;
  border: 1px solid rgba(176, 125, 75, 0.15);
  border-radius: 8px;
  background: rgba(176, 125, 75, 0.04);
  color: var(--text-dim, #999);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: background 0.25s ease, border-color 0.25s ease, color 0.25s ease;
  flex-shrink: 0;
}

.toc-back-btn:hover {
  background: rgba(176, 125, 75, 0.1);
  border-color: rgba(176, 125, 75, 0.3);
  color: var(--accent-copper-deep, #8b6540);
}

.toc-back-btn:active {
  transform: scale(0.94);
}

.toc-back-chevron {
  width: 7px;
  height: 7px;
  border-left: 2px solid currentColor;
  border-bottom: 2px solid currentColor;
  transform: rotate(45deg);
  margin-left: 2px;
}

.toc-list {
  flex: 1;
  overflow-y: auto;
  display: flex;
  flex-direction: column;
  gap: 1px;
}

.toc-entry {
  display: flex;
  align-items: center;
  padding: 7px 10px;
  border-radius: 6px;
  cursor: pointer;
  transition: background 0.15s;
  border-left: 3px solid transparent;
  gap: 6px;
}

.toc-entry:hover {
  background: rgba(176, 125, 75, 0.06);
}

.toc-entry.active {
  background: rgba(176, 125, 75, 0.1);
  border-left-color: var(--accent-copper, #c09060);
}

.toc-entry--chapter {
  font-weight: 500;
}

.toc-entry--block {
  padding-left: 32px;
  font-size: 12px;
  color: var(--text-dim, #999);
  border-left: none;
}

.toc-entry--muted .toc-label {
  color: var(--text-dim, #999);
  font-style: italic;
}

.toc-toggle-btn {
  width: 18px;
  height: 18px;
  border: none;
  background: transparent;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
  padding: 0;
  color: var(--text-dim, #999);
}

.toc-toggle-icon {
  font-size: 10px;
  transition: transform 0.15s;
  display: inline-block;
}

.toc-toggle-icon.expanded {
  transform: rotate(90deg);
}

.toc-label {
  font-size: 14px;
  color: var(--text-main, #1a1a1a);
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.toc-label--chapter {
  font-weight: 600;
}

.toc-meta {
  font-size: 11px;
  color: var(--text-dim, #999);
  white-space: nowrap;
  flex-shrink: 0;
}

.toc-actions {
  display: flex;
  gap: 2px;
  opacity: 0;
  transition: opacity 0.15s;
  flex-shrink: 0;
}

.toc-entry:hover .toc-actions {
  opacity: 1;
}

.toc-action-btn {
  width: 22px;
  height: 22px;
  border: none;
  background: transparent;
  color: var(--text-dim, #999);
  cursor: pointer;
  font-size: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 4px;
}

.toc-action-btn:hover {
  color: var(--accent-copper, #c09060);
  background: rgba(176, 125, 75, 0.08);
}

.toc-action-btn--danger:hover {
  color: #c05050;
  background: rgba(224, 80, 80, 0.08);
}

.toc-children {
  margin-left: 8px;
  border-left: 1px solid var(--line-soft, #e0dcd4);
}

.toc-empty-hint {
  padding: 4px 32px;
  font-size: 11px;
  color: var(--text-dim, #bbb);
  font-style: italic;
}

.toc-block-label {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.toc-block-actions {
  opacity: 0;
  transition: opacity 0.15s;
  flex-shrink: 0;
}

.toc-entry--block:hover .toc-block-actions {
  opacity: 1;
}


.toc-new {
  display: flex;
  gap: 6px;
  padding-top: 8px;
  border-top: 1px solid var(--line-soft, #e0dcd4);
}


.toc-stats-bar {
  display: flex;
  gap: 12px;
  padding: 8px 0;
  border-top: 1px solid var(--line-soft, #e0dcd4);
}

.toc-stat-pill {
  background: rgba(176, 125, 75, 0.08);
  border-radius: 12px;
  padding: 3px 10px;
  font-size: 12px;
  color: var(--accent-copper-deep, #8b6540);
  font-weight: 500;
}

.toc-stat-pill small {
  font-weight: 400;
  opacity: 0.7;
}

.toc-actions-bar {
  display: flex;
  gap: 6px;
}
</style>

// frontend/src/pages/writer/manuscript-toc-panel.tsx
/**
 * ManuscriptTocPanel — table of contents sidebar for manuscript view.
 * Supports chapter CRUD, block reordering, and export.
 */

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { ChevronLeft, ChevronRight } from "lucide-react";
import type { ManuscriptChapter, ManuscriptBlockItem } from "./use-writer-state";

interface ManuscriptTocPanelProps {
  chapters: ManuscriptChapter[];
  blocks: ManuscriptBlockItem[];
  selectedChapterId: string | null;
  totalWords: number;
  totalBlocks: number;
  untaggedCount: number;
  onJump: (chapterId: string | null) => void;
  onCreateChapter: (name: string) => void;
  onRenameChapter: (chapterId: string, newTitle: string) => void;
  onDeleteChapter: (chapterId: string) => void;
  onMoveBlock: (blockId: string, targetChapterId: string | null) => void;
  onExport: (format: string) => void;
  onBack: () => void;
}

export function ManuscriptTocPanel({
  chapters,
  blocks,
  selectedChapterId,
  totalWords,
  totalBlocks,
  untaggedCount,
  onJump,
  onCreateChapter,
  onRenameChapter,
  onDeleteChapter,
  onMoveBlock,
  onExport,
  onBack,
}: ManuscriptTocPanelProps) {
  const [newChapterName, setNewChapterName] = React.useState("");
  const [renamingId, setRenamingId] = React.useState<string | null>(null);
  const [renameValue, setRenameValue] = React.useState("");
  const [expandedChapters, setExpandedChapters] = React.useState<Set<string>>(
    new Set(),
  );
  const renameInputRef = React.useRef<HTMLInputElement>(null);

  const untaggedBlocks = React.useMemo(
    () => blocks.filter((b) => !b.chapter_id),
    [blocks],
  );

  const moveTargetOptions = React.useMemo(
    () => [
      ...chapters.map((c) => ({ label: c.title || "未命名", value: c.chapter_id })),
      { label: "未归类", value: "__unassign__" },
    ],
    [chapters],
  );

  function getBlocksForChapter(chapterId: string) {
    return blocks.filter((b) => b.chapter_id === chapterId);
  }

  function blockLabel(block: ManuscriptBlockItem): string {
    if (block.summary)
      return block.summary.slice(0, 40) + (block.summary.length > 40 ? "..." : "");
    if (block.content)
      return block.content.slice(0, 40) + (block.content.length > 40 ? "..." : "");
    return `段落 #${block.block_order}`;
  }

  function toggleExpand(id: string) {
    setExpandedChapters((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  function startRename(ch: ManuscriptChapter) {
    setRenamingId(ch.chapter_id);
    setRenameValue(ch.title || "");
    setTimeout(() => renameInputRef.current?.focus(), 50);
  }

  function commitRename(chapterId: string) {
    const newTitle = renameValue.trim();
    if (newTitle) onRenameChapter(chapterId, newTitle);
    setRenamingId(null);
  }

  function handleCreate() {
    const name = newChapterName.trim();
    if (!name) return;
    onCreateChapter(name);
    setNewChapterName("");
  }

  function handleMoveBlock(
    blockId: string,
    targetValue: string | null,
    _currentValue: string,
  ) {
    if (!targetValue || targetValue === _currentValue) return;
    onMoveBlock(blockId, targetValue === "__unassign__" ? null : targetValue);
  }

  return (
    <div className="flex h-full flex-col gap-2 overflow-hidden p-3">
      {/* Header */}
      <div className="flex items-center gap-2.5">
        <button
          type="button"
          className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg border border-border/40 text-muted-foreground transition-colors hover:bg-muted"
          onClick={onBack}
          title="返回写作模式"
        >
          <ChevronLeft className="h-4 w-4" />
        </button>
        <div>
          <p className="text-[10px] uppercase tracking-widest text-muted-foreground/50">
            MANUSCRIPT
          </p>
          <h2 className="text-base font-bold">稿件目录</h2>
        </div>
      </div>

      {/* List */}
      <div className="flex flex-1 flex-col gap-px overflow-y-auto">
        {/* All entry */}
        <button
          type="button"
          className={`flex items-center gap-1.5 rounded-md border-l-[3px] px-2.5 py-1.5 text-sm transition-colors ${
            !selectedChapterId
              ? "border-l-primary bg-primary/5"
              : "border-l-transparent hover:bg-muted/50"
          }`}
          onClick={() => onJump(null)}
        >
          <span className="flex-1 text-left font-medium">全部</span>
          <span className="text-[11px] text-muted-foreground">{totalBlocks} 段</span>
        </button>

        {/* Chapters */}
        {chapters.map((ch) => (
          <div key={ch.chapter_id}>
            <div
              className={`group flex items-center gap-1.5 rounded-md border-l-[3px] px-2.5 py-1.5 text-sm transition-colors ${
                selectedChapterId === ch.chapter_id
                  ? "border-l-primary bg-primary/5"
                  : "border-l-transparent hover:bg-muted/50"
              }`}
            >
              <button
                type="button"
                className="flex h-4 w-4 shrink-0 items-center justify-center text-muted-foreground"
                onClick={(e) => {
                  e.stopPropagation();
                  toggleExpand(ch.chapter_id);
                }}
              >
                {expandedChapters.has(ch.chapter_id) ? (
                  <ChevronRight className="h-2.5 w-2.5 rotate-90 transition-transform" />
                ) : (
                  <ChevronRight className="h-2.5 w-2.5 transition-transform" />
                )}
              </button>

              {renamingId === ch.chapter_id ? (
                <Input
                  ref={renameInputRef}
                  className="h-6 flex-1 text-sm"
                  value={renameValue}
                  onChange={(e) => setRenameValue(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") commitRename(ch.chapter_id);
                    if (e.key === "Escape") setRenamingId(null);
                  }}
                  onBlur={() => commitRename(ch.chapter_id)}
                  onClick={(e) => e.stopPropagation()}
                />
              ) : (
                <>
                  <button
                    type="button"
                    className="min-w-0 flex-1 truncate text-left font-semibold"
                    onClick={() => onJump(ch.chapter_id)}
                  >
                    {ch.title || "未命名章节"}
                  </button>
                  <span className="shrink-0 text-[11px] text-muted-foreground">
                    {ch.blockCount} 段 &middot; {ch.wordCount} 字
                  </span>
                  <div className="flex shrink-0 gap-0.5 opacity-0 transition-opacity group-hover:opacity-100">
                    <button
                      type="button"
                      className="rounded px-1 text-xs text-muted-foreground hover:bg-muted hover:text-primary"
                      onClick={(e) => {
                        e.stopPropagation();
                        startRename(ch);
                      }}
                      title="重命名"
                    >
                      &#9998;
                    </button>
                    <button
                      type="button"
                      className="rounded px-1 text-xs text-muted-foreground hover:bg-destructive/10 hover:text-destructive"
                      onClick={(e) => {
                        e.stopPropagation();
                        onDeleteChapter(ch.chapter_id);
                      }}
                      title="删除章节"
                    >
                      &#10005;
                    </button>
                  </div>
                </>
              )}
            </div>

            {/* Expanded blocks */}
            {expandedChapters.has(ch.chapter_id) && (
              <div className="ml-2 border-l border-border/40">
                {getBlocksForChapter(ch.chapter_id).map((block) => (
                  <div
                    key={block.block_id}
                    className="group/block flex items-center gap-1.5 border-l-0 py-1 pl-8 pr-2 text-xs text-muted-foreground"
                    onClick={() => onJump(ch.chapter_id)}
                  >
                    <span className="min-w-0 flex-1 truncate">
                      {blockLabel(block)}
                    </span>
                    <div
                      className="shrink-0 opacity-0 transition-opacity group-hover/block:opacity-100"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <Select
                        value={ch.chapter_id}
                        onValueChange={(val) =>
                          handleMoveBlock(block.block_id, val, ch.chapter_id)
                        }
                      >
                        <SelectTrigger className="h-5 w-[90px] text-[10px]">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {moveTargetOptions.map((opt) => (
                            <SelectItem key={opt.value} value={opt.value}>
                              {opt.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                ))}
                {getBlocksForChapter(ch.chapter_id).length === 0 && (
                  <div className="py-1 pl-8 text-[11px] italic text-muted-foreground">
                    暂无段落
                  </div>
                )}
              </div>
            )}
          </div>
        ))}

        {/* Untagged */}
        {untaggedCount > 0 && (
          <div>
            <button
              type="button"
              className={`flex w-full items-center gap-1.5 rounded-md border-l-[3px] px-2.5 py-1.5 text-sm italic transition-colors ${
                selectedChapterId === "__untagged__"
                  ? "border-l-primary bg-primary/5"
                  : "border-l-transparent hover:bg-muted/50"
              }`}
              onClick={() => onJump("__untagged__")}
            >
              <button
                type="button"
                className="flex h-4 w-4 shrink-0 items-center justify-center text-muted-foreground"
                onClick={(e) => {
                  e.stopPropagation();
                  toggleExpand("__untagged__");
                }}
              >
                {expandedChapters.has("__untagged__") ? (
                  <ChevronRight className="h-2.5 w-2.5 rotate-90" />
                ) : (
                  <ChevronRight className="h-2.5 w-2.5" />
                )}
              </button>
              <span className="flex-1 text-left text-muted-foreground">
                未归类
              </span>
              <span className="text-[11px] text-muted-foreground">
                {untaggedCount} 段
              </span>
            </button>

            {expandedChapters.has("__untagged__") && (
              <div className="ml-2 border-l border-border/40">
                {untaggedBlocks.map((block) => (
                  <div
                    key={block.block_id}
                    className="group/block flex items-center gap-1.5 py-1 pl-8 pr-2 text-xs text-muted-foreground"
                  >
                    <span className="min-w-0 flex-1 truncate">
                      {blockLabel(block)}
                    </span>
                    <div
                      className="shrink-0 opacity-0 transition-opacity group-hover/block:opacity-100"
                      onClick={(e) => e.stopPropagation()}
                    >
                      <Select
                        value="__unassign__"
                        onValueChange={(val) =>
                          handleMoveBlock(block.block_id, val, "__unassign__")
                        }
                      >
                        <SelectTrigger className="h-5 w-[90px] text-[10px]">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          {moveTargetOptions.map((opt) => (
                            <SelectItem key={opt.value} value={opt.value}>
                              {opt.label}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        )}
      </div>

      {/* New chapter input */}
      <div className="border-t border-border/40 pt-2">
        <div className="flex gap-1.5">
          <Input
            className="h-8 flex-1 text-sm"
            placeholder="新章节名称..."
            value={newChapterName}
            onChange={(e) => setNewChapterName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleCreate()}
          />
          <Button
            size="sm"
            variant="ghost"
            disabled={!newChapterName.trim()}
            onClick={handleCreate}
          >
            添加
          </Button>
        </div>
      </div>

      {/* Stats */}
      <div className="flex gap-3 border-t border-border/40 pt-2">
        <span className="rounded-xl bg-primary/5 px-2.5 py-0.5 text-xs font-medium text-primary">
          {totalWords} <small className="font-normal opacity-70">字</small>
        </span>
        <span className="rounded-xl bg-primary/5 px-2.5 py-0.5 text-xs font-medium text-primary">
          {chapters.length} <small className="font-normal opacity-70">章</small>
        </span>
        <span className="rounded-xl bg-primary/5 px-2.5 py-0.5 text-xs font-medium text-primary">
          {totalBlocks} <small className="font-normal opacity-70">段</small>
        </span>
      </div>

      {/* Export */}
      <div className="flex gap-1.5">
        <Button size="sm" variant="outline" onClick={() => onExport("txt")}>
          导出 TXT
        </Button>
        <Button size="sm" variant="outline" onClick={() => onExport("md")}>
          导出 MD
        </Button>
      </div>
    </div>
  );
}
