// frontend/src/views/writer/OutlineView.vue
<template>
  <div class="outline-view">
    <div class="outline-header">
      <h3 class="outline-title title-ancient">章节大纲</h3>
      <span class="outline-count">{{ displayOutline.length }} 个场景</span>
      <div class="outline-header-actions">
        <n-input
          v-if="!previewOutline"
          v-model:value="labelInput"
          class="outline-label-input"
          placeholder="版本标注（可选）"
          size="small"
        />
        <n-button
          v-if="!previewOutline"
          size="small"
          type="primary"
          :disabled="!dirty"
          @click="handleSave"
        >保存大纲</n-button>
        <n-button
          size="small"
          :type="showHistory ? 'primary' : 'default'"
          :quaternary="!showHistory"
          @click="toggleHistory"
        >历史版本</n-button>
      </div>
    </div>

    <!-- Preview banner -->
    <div v-if="previewOutline" class="outline-preview-banner">
      <span>正在预览历史版本</span>
      <n-button size="small" @click="emit('restore')">回退到此版本</n-button>
      <n-button size="small" @click="emit('cancel-preview')">取消预览</n-button>
    </div>

    <!-- Version history panel -->
    <div v-if="showHistory" class="outline-version-list">
      <div v-if="!versions.length" class="outline-version-empty">暂无历史版本</div>
      <div
        v-for="(ver, idx) in versions"
        :key="ver.version_id"
        class="outline-version-item"
        @click="emit('load-versions', ver.version_id)"
      >
        <span class="outline-version-idx">{{ versions.length - idx }}</span>
        <span class="outline-version-label">{{ ver.label || '自动快照' }}</span>
        <span class="outline-version-time">{{ formatTime(ver.created_at) }}</span>
      </div>
    </div>

    <!-- Scene list (current or preview) -->
    <div class="outline-list">
      <div
        v-for="(scene, idx) in displayOutline"
        :key="idx"
        class="outline-item"
      >
        <div class="outline-item-header">
          <span class="outline-order">{{ scene.scene_order }}</span>
          <n-input
            v-if="!previewOutline"
            v-model:value="scene.title"
            class="outline-item-title-input"
            placeholder="场景标题"
            @input="dirty = true"
          />
          <span v-else class="outline-item-title outline-item-title--readonly">{{ scene.title }}</span>
          <div v-if="!previewOutline" class="outline-item-actions">
            <n-button size="tiny" quaternary :disabled="idx === 0" @click="moveUp(idx)" title="上移"><Icon icon="icon-park-outline:up" width="14" /></n-button>
            <n-button size="tiny" quaternary :disabled="idx === displayOutline.length - 1" @click="moveDown(idx)" title="下移"><Icon icon="icon-park-outline:down" width="14" /></n-button>
            <n-button size="tiny" quaternary @click="removeScene(idx)" title="删除"><Icon icon="icon-park-outline:close-small" width="14" /></n-button>
          </div>
        </div>

        <div class="outline-item-fields">
          <div class="outline-field">
            <label>POV</label>
            <n-input v-if="!previewOutline" v-model:value="scene.pov" placeholder="视角角色" size="small" @input="dirty = true" />
            <span v-else class="outline-field-readonly">{{ scene.pov || '—' }}</span>
          </div>
          <div class="outline-field outline-field--wide">
            <label>概述</label>
            <n-input
              v-if="!previewOutline"
              v-model:value="scene.summary"
              type="textarea"
              :rows="2"
              placeholder="场景概述..."
              size="small"
              @input="dirty = true"
            />
            <p v-else class="outline-field-readonly">{{ scene.summary || '—' }}</p>
          </div>
          <div class="outline-field outline-field--wide">
            <label>关键事件</label>
            <div class="outline-events">
              <template v-if="!previewOutline">
                <div v-for="(ev, ei) in scene.key_events" :key="ei" class="outline-event-row">
                  <n-input
                    :value="ev"
                    placeholder="事件描述"
                    size="small"
                    @update:value="val => updateEvent(idx, ei, val)"
                  />
                  <n-button size="tiny" quaternary @click="removeEvent(idx, ei)"><Icon icon="icon-park-outline:close-small" width="12" /></n-button>
                </div>
                <n-button size="tiny" dashed @click="addEvent(idx)">+ 事件</n-button>
              </template>
              <template v-else>
                <div v-for="(ev, ei) in scene.key_events" :key="ei" class="outline-event-row">
                  <span class="outline-field-readonly">{{ ev }}</span>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>
    </div>

    <n-button v-if="!previewOutline" class="outline-add-scene" dashed block @click="addScene">+ 添加场景</n-button>
  </div>
</template>

<script setup>
import { ref, watch, computed } from "vue";
import { NButton, NInput } from "naive-ui";
import { Icon } from "@iconify/vue";

const props = defineProps({
  outline: { type: Array, default: () => [] },
  chapterId: { type: String, default: "" },
  projectId: { type: String, default: "" },
  versions: { type: Array, default: () => [] },
  previewOutline: { type: Array, default: null },
});

const emit = defineEmits(["save", "load-versions", "restore", "cancel-preview"]);

const localOutline = ref(JSON.parse(JSON.stringify(props.outline)));
const dirty = ref(false);
const showHistory = ref(false);
const labelInput = ref("");

const previewRef = computed(() => props.previewOutline);
const displayOutline = computed(() => {
  return previewRef.value || localOutline.value;
});

watch(() => props.outline, (val) => {
  localOutline.value = JSON.parse(JSON.stringify(val));
  dirty.value = false;
}, { deep: true });

function renumber() {
  localOutline.value.forEach((s, i) => { s.scene_order = i + 1; });
}

function moveUp(idx) {
  if (idx <= 0) return;
  const arr = localOutline.value;
  [arr[idx - 1], arr[idx]] = [arr[idx], arr[idx - 1]];
  renumber();
  dirty.value = true;
}

function moveDown(idx) {
  const arr = localOutline.value;
  if (idx >= arr.length - 1) return;
  [arr[idx], arr[idx + 1]] = [arr[idx + 1], arr[idx]];
  renumber();
  dirty.value = true;
}

function removeScene(idx) {
  localOutline.value.splice(idx, 1);
  renumber();
  dirty.value = true;
}

function addScene() {
  localOutline.value.push({
    scene_order: localOutline.value.length + 1,
    title: "",
    summary: "",
    pov: "",
    key_events: [],
  });
  dirty.value = true;
}

function updateEvent(sceneIdx, eventIdx, value) {
  localOutline.value[sceneIdx].key_events[eventIdx] = value;
  dirty.value = true;
}

function removeEvent(sceneIdx, eventIdx) {
  localOutline.value[sceneIdx].key_events.splice(eventIdx, 1);
  dirty.value = true;
}

function addEvent(sceneIdx) {
  if (!localOutline.value[sceneIdx].key_events) {
    localOutline.value[sceneIdx].key_events = [];
  }
  localOutline.value[sceneIdx].key_events.push("");
  dirty.value = true;
}

function handleSave() {
  emit("save", JSON.parse(JSON.stringify(localOutline.value)), labelInput.value);
  labelInput.value = "";
}

function toggleHistory() {
  showHistory.value = !showHistory.value;
  if (showHistory.value) {
    emit("load-versions");
  }
}

function formatTime(iso) {
  if (!iso) return "";
  const d = new Date(iso);
  const pad = (n) => String(n).padStart(2, "0");
  return `${d.getMonth() + 1}/${d.getDate()} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
</script>

<style scoped>
.outline-view {
  display: flex;
  flex-direction: column;
  height: 100%;
  padding: 14px;
  overflow-y: auto;
}

.outline-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 10px;
}

.outline-title {
  margin: 0;
  font-size: 16px;
}

.outline-count {
  font-size: 13px;
  color: var(--text-dim, #999);
}

.outline-header-actions {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-left: auto;
}

.outline-label-input {
  width: 140px;
}

.outline-preview-banner {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 10px 14px;
  margin-bottom: 12px;
  background: rgba(176, 125, 75, 0.08);
  border: 1px solid var(--accent-copper, #c09060);
  border-radius: 8px;
  font-size: 13px;
  color: var(--accent-copper, #c09060);
}

.outline-version-list {
  display: flex;
  flex-direction: column;
  gap: 4px;
  margin-bottom: 14px;
  padding: 10px;
  background: #faf9f7;
  border: 1px solid var(--line-soft, #e0dcd4);
  border-radius: 8px;
  max-height: 200px;
  overflow-y: auto;
}

.outline-version-empty {
  font-size: 13px;
  color: var(--text-dim, #999);
  text-align: center;
  padding: 8px;
}

.outline-version-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 6px 10px;
  border-radius: 6px;
  cursor: pointer;
  font-size: 13px;
}

.outline-version-item:hover {
  background: rgba(176, 125, 75, 0.08);
}

.outline-version-idx {
  width: 24px;
  height: 24px;
  border-radius: 50%;
  background: var(--line-soft, #e0dcd4);
  font-size: 11px;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.outline-version-label {
  flex: 1;
  color: var(--text-main, #1a1a1a);
}

.outline-version-time {
  font-size: 11px;
  color: var(--text-dim, #999);
  flex-shrink: 0;
}

.outline-list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.outline-item {
  border: 1px solid var(--line-soft, #e0dcd4);
  border-radius: 8px;
  padding: 10px 12px;
  background: #fff;
}

.outline-item-header {
  display: flex;
  align-items: center;
  gap: 10px;
  margin-bottom: 10px;
}

.outline-order {
  width: 28px;
  height: 28px;
  border-radius: 50%;
  background: var(--accent-copper, #c09060);
  color: #fff;
  font-size: 13px;
  font-weight: 600;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.outline-item-title-input {
  flex: 1;
}

.outline-item-title--readonly {
  flex: 1;
  padding: 4px 8px;
  font-size: 15px;
  font-weight: 500;
  color: var(--text-main, #1a1a1a);
}

.outline-item-actions {
  display: flex;
  gap: 4px;
  flex-shrink: 0;
}

.outline-item-fields {
  display: flex;
  flex-wrap: wrap;
  gap: 10px;
}

.outline-field {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.outline-field label {
  font-size: 11px;
  color: var(--text-dim, #999);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.outline-field--wide {
  flex: 1 1 100%;
}

.outline-field-readonly {
  font-size: 13px;
  color: var(--text-main, #1a1a1a);
  padding: 4px 0;
}

.outline-events {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.outline-event-row {
  display: flex;
  gap: 4px;
  align-items: center;
}

.outline-add-scene {
  margin-top: 12px;
}
</style>

// frontend/src/pages/writer/outline-view.tsx
/**
 * OutlineView — chapter outline editor with version history.
 */

import * as React from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { ChevronUp, ChevronDown, X, Plus } from "lucide-react";
import type { OutlineScene, OutlineVersionItem } from "./use-writer-state";

interface OutlineViewProps {
  outline: OutlineScene[];
  chapterId: string;
  projectId: string;
  versions: OutlineVersionItem[];
  previewOutline: OutlineScene[] | null;
  onSave: (outline: OutlineScene[], label: string) => void;
  onLoadVersions: (versionId?: string) => void;
  onRestore: () => void;
  onCancelPreview: () => void;
}

export function OutlineView({
  outline,
  versions,
  previewOutline,
  onSave,
  onLoadVersions,
  onRestore,
  onCancelPreview,
}: OutlineViewProps) {
  const [localOutline, setLocalOutline] = React.useState<OutlineScene[]>(() =>
    JSON.parse(JSON.stringify(outline)),
  );
  const [dirty, setDirty] = React.useState(false);
  const [showHistory, setShowHistory] = React.useState(false);
  const [labelInput, setLabelInput] = React.useState("");

  const displayOutline = previewOutline ?? localOutline;

  React.useEffect(() => {
    setLocalOutline(JSON.parse(JSON.stringify(outline)));
    setDirty(false);
  }, [outline]);

  function renumber(arr: OutlineScene[]) {
    arr.forEach((s, i) => {
      s.scene_order = i + 1;
    });
  }

  function moveUp(idx: number) {
    if (idx <= 0) return;
    const arr = [...localOutline];
    const temp = arr[idx]!;
    arr[idx] = arr[idx - 1]!;
    arr[idx - 1] = temp;
    renumber(arr);
    setLocalOutline(arr);
    setDirty(true);
  }

  function moveDown(idx: number) {
    if (idx >= localOutline.length - 1) return;
    const arr = [...localOutline];
    const temp = arr[idx]!;
    arr[idx] = arr[idx + 1]!;
    arr[idx + 1] = temp;
    renumber(arr);
    setLocalOutline(arr);
    setDirty(true);
  }

  function removeScene(idx: number) {
    const arr = localOutline.filter((_, i) => i !== idx);
    renumber(arr);
    setLocalOutline(arr);
    setDirty(true);
  }

  function addScene() {
    setLocalOutline((prev) => [
      ...prev,
      {
        scene_order: prev.length + 1,
        title: "",
        summary: "",
        pov: "",
        key_events: [],
      },
    ]);
    setDirty(true);
  }

  function updateField(idx: number, field: keyof OutlineScene, value: unknown) {
    setLocalOutline((prev) => {
      const arr = [...prev];
      const existing = arr[idx]!;
      arr[idx] = { scene_order: existing.scene_order, title: existing.title, summary: existing.summary, pov: existing.pov, key_events: existing.key_events, [field]: value };
      return arr;
    });
    setDirty(true);
  }

  function updateEvent(sceneIdx: number, eventIdx: number, value: string) {
    setLocalOutline((prev) => {
      const arr = [...prev];
      const existing = arr[sceneIdx]!;
      const events = [...existing.key_events];
      events[eventIdx] = value;
      arr[sceneIdx] = { scene_order: existing.scene_order, title: existing.title, summary: existing.summary, pov: existing.pov, key_events: events };
      return arr;
    });
    setDirty(true);
  }

  function removeEvent(sceneIdx: number, eventIdx: number) {
    setLocalOutline((prev) => {
      const arr = [...prev];
      const existing = arr[sceneIdx]!;
      const events = existing.key_events.filter((_, i) => i !== eventIdx);
      arr[sceneIdx] = { scene_order: existing.scene_order, title: existing.title, summary: existing.summary, pov: existing.pov, key_events: events };
      return arr;
    });
    setDirty(true);
  }

  function addEvent(sceneIdx: number) {
    setLocalOutline((prev) => {
      const arr = [...prev];
      const existing = arr[sceneIdx]!;
      arr[sceneIdx] = {
        scene_order: existing.scene_order,
        title: existing.title,
        summary: existing.summary,
        pov: existing.pov,
        key_events: [...(existing.key_events || []), ""],
      };
      return arr;
    });
    setDirty(true);
  }

  function handleSave() {
    onSave(JSON.parse(JSON.stringify(localOutline)), labelInput);
    setLabelInput("");
  }

  function toggleHistory() {
    setShowHistory((prev) => !prev);
    if (!showHistory) onLoadVersions();
  }

  function formatTime(iso: string) {
    if (!iso) return "";
    const d = new Date(iso);
    const pad = (n: number) => String(n).padStart(2, "0");
    return `${d.getMonth() + 1}/${d.getDate()} ${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }

  return (
    <div className="flex flex-col gap-2 overflow-y-auto p-3.5">
      {/* Header */}
      <div className="flex flex-wrap items-center gap-2">
        <h3 className="text-base font-bold">章节大纲</h3>
        <span className="text-[13px] text-muted-foreground">
          {displayOutline.length} 个场景
        </span>
        <div className="ml-auto flex items-center gap-2">
          {!previewOutline && (
            <Input
              className="w-[140px]"
              placeholder="版本标注（可选）"
              value={labelInput}
              onChange={(e) => setLabelInput(e.target.value)}
            />
          )}
          {!previewOutline && (
            <Button size="sm" disabled={!dirty} onClick={handleSave}>
              保存大纲
            </Button>
          )}
          <Button
            size="sm"
            variant={showHistory ? "default" : "outline"}
            onClick={toggleHistory}
          >
            历史版本
          </Button>
        </div>
      </div>

      {/* Preview banner */}
      {previewOutline && (
        <div className="flex items-center gap-2.5 rounded-lg border border-primary/30 bg-primary/5 px-3.5 py-2.5 text-[13px] text-primary">
          <span>正在预览历史版本</span>
          <Button size="sm" variant="outline" onClick={onRestore}>
            回退到此版本
          </Button>
          <Button size="sm" variant="ghost" onClick={onCancelPreview}>
            取消预览
          </Button>
        </div>
      )}

      {/* Version history */}
      {showHistory && (
        <div className="flex max-h-[200px] flex-col gap-1 overflow-y-auto rounded-lg border border-border/40 bg-muted/30 p-2.5">
          {versions.length === 0 ? (
            <div className="py-2 text-center text-[13px] text-muted-foreground">
              暂无历史版本
            </div>
          ) : (
            versions.map((ver, idx) => (
              <button
                key={ver.version_id}
                type="button"
                className="flex items-center gap-2 rounded-md px-2.5 py-1.5 text-[13px] transition-colors hover:bg-muted"
                onClick={() => onLoadVersions(ver.version_id)}
              >
                <span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-border text-[11px] font-semibold">
                  {versions.length - idx}
                </span>
                <span className="flex-1 text-left">{ver.label || "自动快照"}</span>
                <span className="text-[11px] text-muted-foreground">
                  {formatTime(ver.created_at)}
                </span>
              </button>
            ))
          )}
        </div>
      )}

      {/* Scene list */}
      <div className="flex flex-col gap-2">
        {displayOutline.map((scene, idx) => (
          <div
            key={idx}
            className="rounded-lg border border-border/40 bg-card p-3"
          >
            <div className="mb-2.5 flex items-center gap-2.5">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary text-[13px] font-semibold text-primary-foreground">
                {scene.scene_order}
              </span>
              {!previewOutline ? (
                <Input
                  className="flex-1"
                  placeholder="场景标题"
                  value={scene.title}
                  onChange={(e) => updateField(idx, "title", e.target.value)}
                />
              ) : (
                <span className="flex-1 px-2 text-[15px] font-medium">
                  {scene.title}
                </span>
              )}
              {!previewOutline && (
                <div className="flex gap-1 shrink-0">
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-6 w-6"
                    disabled={idx === 0}
                    onClick={() => moveUp(idx)}
                  >
                    <ChevronUp className="h-3.5 w-3.5" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-6 w-6"
                    disabled={idx === displayOutline.length - 1}
                    onClick={() => moveDown(idx)}
                  >
                    <ChevronDown className="h-3.5 w-3.5" />
                  </Button>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-6 w-6"
                    onClick={() => removeScene(idx)}
                  >
                    <X className="h-3.5 w-3.5" />
                  </Button>
                </div>
              )}
            </div>

            <div className="flex flex-wrap gap-2.5">
              <div className="flex flex-col gap-1">
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  POV
                </span>
                {!previewOutline ? (
                  <Input
                    className="w-[160px]"
                    placeholder="视角角色"
                    value={scene.pov}
                    onChange={(e) => updateField(idx, "pov", e.target.value)}
                  />
                ) : (
                  <span className="text-[13px]">{scene.pov || "--"}</span>
                )}
              </div>
              <div className="flex min-w-0 flex-1 flex-col gap-1">
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  概述
                </span>
                {!previewOutline ? (
                  <Textarea
                    className="min-h-[50px]"
                    placeholder="场景概述..."
                    value={scene.summary}
                    onChange={(e) =>
                      updateField(idx, "summary", e.target.value)
                    }
                  />
                ) : (
                  <p className="text-[13px]">{scene.summary || "--"}</p>
                )}
              </div>
              <div className="flex min-w-0 basis-full flex-col gap-1">
                <span className="text-[11px] uppercase tracking-wider text-muted-foreground">
                  关键事件
                </span>
                <div className="flex flex-col gap-1">
                  {!previewOutline ? (
                    <>
                      {(scene.key_events || []).map((ev, ei) => (
                        <div key={ei} className="flex items-center gap-1">
                          <Input
                            className="flex-1"
                            placeholder="事件描述"
                            value={ev}
                            onChange={(e) =>
                              updateEvent(idx, ei, e.target.value)
                            }
                          />
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6 shrink-0"
                            onClick={() => removeEvent(idx, ei)}
                          >
                            <X className="h-3 w-3" />
                          </Button>
                        </div>
                      ))}
                      <Button
                        variant="outline"
                        size="sm"
                        className="w-fit"
                        onClick={() => addEvent(idx)}
                      >
                        <Plus className="mr-1 h-3 w-3" /> 事件
                      </Button>
                    </>
                  ) : (
                    (scene.key_events || []).map((ev, ei) => (
                      <div key={ei} className="text-[13px]">
                        {ev}
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>

      {!previewOutline && (
        <Button variant="outline" className="mt-2 w-full" onClick={addScene}>
          <Plus className="mr-1 h-4 w-4" /> 添加场景
        </Button>
      )}
    </div>
  );
}
