// frontend/src/views/writer/SceneEditor.vue
<template>
  <div class="scene-editor">
    <div v-if="streaming" class="scene-editor-content scene-editor-content--streaming">
      <div class="streaming-text" v-text="content"></div>
      <span class="streaming-cursor">▊</span>
    </div>
    <textarea
      v-else
      class="scene-editor-content scene-editor-textarea"
      :value="content"
      @input="$emit('update', $event.target.value)"
      :readonly="readonly"
      placeholder="场景内容将在此处显示..."
    ></textarea>

    <!-- Floating toolbar on text selection -->
    <div
      v-if="showToolbar"
      class="scene-floating-toolbar"
      :style="{ top: toolbarPos.top + 'px', left: toolbarPos.left + 'px' }"
    >
      <button @click="handleCommitSelection">提交选中</button>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, onBeforeUnmount } from "vue";

defineProps({
  content: { type: String, default: "" },
  streaming: { type: Boolean, default: false },
  readonly: { type: Boolean, default: false },
});

const emit = defineEmits(["update", "commit-selection"]);

const showToolbar = ref(false);
const toolbarPos = ref({ top: 0, left: 0 });
let selectedText = "";

function handleSelectionChange() {
  const sel = window.getSelection();
  if (sel && sel.toString().trim().length > 0) {
    selectedText = sel.toString();
    const range = sel.getRangeAt(0);
    const rect = range.getBoundingClientRect();
    toolbarPos.value = {
      top: rect.top - 40,
      left: rect.left + rect.width / 2 - 60,
    };
    showToolbar.value = true;
  } else {
    showToolbar.value = false;
  }
}

function handleCommitSelection() {
  if (selectedText.trim()) {
    emit("commit-selection", selectedText);
    showToolbar.value = false;
  }
}

onMounted(() => {
  document.addEventListener("selectionchange", handleSelectionChange);
});

onBeforeUnmount(() => {
  document.removeEventListener("selectionchange", handleSelectionChange);
});
</script>

<style scoped>
.scene-editor {
  position: relative;
  height: 100%;
  display: flex;
  flex-direction: column;
}
.scene-editor-content {
  flex: 1;
  padding: 20px;
  font-size: 15px;
  line-height: 1.8;
  color: #333;
}
.scene-editor-textarea {
  width: 100%;
  min-height: 400px;
  border: none;
  outline: none;
  resize: vertical;
  font-family: inherit;
  background: transparent;
  box-sizing: border-box;
}
.scene-editor-content--streaming {
  overflow-y: auto;
  white-space: pre-wrap;
  word-wrap: break-word;
}
.streaming-cursor {
  animation: blink 1s step-end infinite;
  color: #409eff;
}
@keyframes blink {
  50% { opacity: 0; }
}
.scene-floating-toolbar {
  position: fixed;
  display: flex;
  gap: 4px;
  background: #333;
  border-radius: 6px;
  padding: 4px 6px;
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
  z-index: 100;
}
.scene-floating-toolbar button {
  background: none;
  border: none;
  color: #fff;
  font-size: 12px;
  padding: 4px 10px;
  cursor: pointer;
  border-radius: 3px;
}
.scene-floating-toolbar button:hover {
  background: rgba(255, 255, 255, 0.15);
}
</style>

// frontend/src/pages/writer/scene-editor.tsx
/**
 * SceneEditor — streaming-aware content editor for the active scene.
 * Displays streaming text with a blinking cursor or an editable textarea.
 */

import * as React from "react";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";

interface SceneEditorProps {
  content: string;
  streaming: boolean;
  readonly?: boolean;
  onUpdate?: (content: string) => void;
  onCommitSelection?: (text: string) => void;
}

export function SceneEditor({
  content,
  streaming,
  readonly,
  onUpdate,
  onCommitSelection,
}: SceneEditorProps) {
  const [showToolbar, setShowToolbar] = React.useState(false);
  const [toolbarPos, setToolbarPos] = React.useState({ top: 0, left: 0 });
  const selectedTextRef = React.useRef("");

  React.useEffect(() => {
    function handleSelectionChange() {
      const sel = window.getSelection();
      if (sel && sel.toString().trim().length > 0) {
        selectedTextRef.current = sel.toString();
        const range = sel.getRangeAt(0);
        const rect = range.getBoundingClientRect();
        setToolbarPos({
          top: rect.top - 40,
          left: rect.left + rect.width / 2 - 60,
        });
        setShowToolbar(true);
      } else {
        setShowToolbar(false);
      }
    }

    document.addEventListener("selectionchange", handleSelectionChange);
    return () =>
      document.removeEventListener("selectionchange", handleSelectionChange);
  }, []);

  function handleCommitSelection() {
    if (selectedTextRef.current.trim() && onCommitSelection) {
      onCommitSelection(selectedTextRef.current);
      setShowToolbar(false);
    }
  }

  return (
    <div className="relative flex h-full min-h-0 flex-1 flex-col">
      {streaming ? (
        <div className="min-h-0 flex-1 overflow-y-auto whitespace-pre-wrap break-words p-3.5 text-sm leading-relaxed text-foreground">
          {content}
          <span className="animate-pulse text-blue-400">&#x2588;</span>
        </div>
      ) : (
        <Textarea
          className="min-h-0 flex-1 resize-none border-0 p-3.5 text-sm leading-relaxed focus-visible:ring-0"
          value={content}
          onChange={(e) => onUpdate?.(e.target.value)}
          readOnly={readonly}
          placeholder="场景内容将在此处显示..."
        />
      )}

      {showToolbar && (
        <div
          className="fixed z-50 flex gap-1 rounded-md bg-gray-800 px-1.5 py-1 shadow-lg"
          style={{ top: toolbarPos.top, left: toolbarPos.left }}
        >
          <Button
            variant="ghost"
            size="sm"
            className="h-6 text-xs text-white hover:text-white"
            onClick={handleCommitSelection}
          >
            提交选中
          </Button>
        </div>
      )}
    </div>
  );
}
