// frontend/src/views/story-graph/WorldOverviewDashboard.vue
<template>
  <div class="overview-dashboard">
    <!-- 卡片 1: Hero -->
    <section class="hero-card workbench-card">
      <div class="hero-main">
        <div class="hero-title-row">
          <h2 class="hero-title">{{ overview.hero.projectName }}</h2>
          <span class="hero-badge">世界速览</span>
        </div>
        <div class="hero-stats">
          <div class="stat"><span class="num">{{ overview.hero.totalNodes }}</span><span class="lbl">实体</span></div>
          <div class="stat"><span class="num">{{ overview.hero.totalEdges }}</span><span class="lbl">关联</span></div>
          <div class="stat"><span class="num">{{ overview.hero.typeCount }}</span><span class="lbl">设定类</span></div>
          <div class="stat"><span class="num">{{ overview.hero.eventCount }}</span><span class="lbl">事件</span></div>
        </div>
        <p class="hero-headline">{{ overview.hero.headline }}</p>
        <div v-if="overview.hero.protagonistNames.length || overview.hero.majorOrgNames.length" class="hero-tags">
          <span v-for="n in overview.hero.protagonistNames" :key="'p' + n" class="tag protagonist">⭐ {{ n }}</span>
          <span v-for="n in overview.hero.majorOrgNames" :key="'o' + n" class="tag org">⚑ {{ n }}</span>
        </div>
      </div>
    </section>

    <!-- 卡片 6: Story Hooks（最高价值，前置）-->
    <section v-if="overview.hooks.length" class="hooks-card workbench-card">
      <header class="card-header">
        <h3>💡 创作锚点</h3>
        <span class="muted">基于图谱派生的可写场景种子 · 共 {{ overview.hooks.length }} 个</span>
      </header>
      <div class="hooks-grid">
        <article v-for="(hook, idx) in overview.hooks" :key="idx" class="hook-item">
          <div class="hook-title">{{ hook.title }}</div>
          <p class="hook-body">{{ hook.body }}</p>
          <div class="hook-meta">
            <span class="involved">涉及：{{ hook.involvedNames.join(" · ") }}</span>
          </div>
          <div class="hook-actions">
            <n-button size="tiny" quaternary @click="focusFirst(hook.involvedIds)">在图谱中查看</n-button>
            <n-button size="tiny" quaternary @click="copyHook(hook)">复制锚点</n-button>
          </div>
        </article>
      </div>
    </section>

    <!-- 卡片 2: Cast Radar -->
    <section class="cast-card workbench-card">
      <header class="card-header">
        <h3>🎭 阵容雷达</h3>
        <span class="muted">共 {{ overview.cast.totalCharacters }} 个角色</span>
      </header>

      <div v-if="overview.cast.protagonist.length" class="cast-row">
        <div class="row-title">主角</div>
        <div class="cast-grid protagonist">
          <article v-for="c in overview.cast.protagonist" :key="c.id" class="cast-card-item major" @click="focusNode(c.id)">
            <div class="name">⭐ {{ c.name }}</div>
            <p v-if="c.summary" class="summary">{{ c.summary }}</p>
            <div class="meta mono">关联 {{ c.degree }}</div>
          </article>
        </div>
      </div>

      <div v-if="overview.cast.major.length" class="cast-row">
        <div class="row-title">主要角色</div>
        <div class="cast-grid">
          <article v-for="c in overview.cast.major" :key="c.id" class="cast-card-item" @click="focusNode(c.id)">
            <div class="name">{{ c.name }}</div>
            <p v-if="c.summary" class="summary">{{ c.summary }}</p>
            <div class="meta mono">关联 {{ c.degree }}</div>
          </article>
        </div>
      </div>

      <details v-if="overview.cast.supporting.length || overview.cast.minor.length" class="cast-row">
        <summary class="row-title">辅助 / 次要角色（{{ overview.cast.supporting.length + overview.cast.minor.length }}）</summary>
        <div class="cast-grid mini">
          <span v-for="c in [...overview.cast.supporting, ...overview.cast.minor]" :key="c.id" class="mini-chip" @click="focusNode(c.id)">
            {{ c.name }}<small> · {{ c.degree }}</small>
          </span>
        </div>
      </details>

      <div v-if="overview.cast.organizations.length" class="cast-row">
        <div class="row-title">组织 / 势力</div>
        <div class="cast-grid">
          <article v-for="o in overview.cast.organizations" :key="o.id" class="cast-card-item org" @click="focusNode(o.id)">
            <div class="name">⚑ {{ o.name }}</div>
            <p v-if="o.summary" class="summary">{{ o.summary }}</p>
            <div class="meta mono">关联 {{ o.degree }}</div>
          </article>
        </div>
      </div>
    </section>

    <!-- 卡片 3: Relationship Highlights -->
    <section class="rel-card workbench-card">
      <header class="card-header">
        <h3>💞 关系亮点</h3>
      </header>
      <div class="rel-grid">
        <div class="rel-col">
          <div class="col-title">核心羁绊 Top 5</div>
          <ol class="rel-list">
            <li v-for="r in overview.highlights.topBonds" :key="r.id" @click="focusEdge(r)">
              <span class="from">{{ r.sourceName }}</span>
              <span class="rel">— {{ r.label }} →</span>
              <span class="to">{{ r.targetName }}</span>
              <span class="weight mono">×{{ r.weight }}</span>
            </li>
            <li v-if="!overview.highlights.topBonds.length" class="empty">暂无</li>
          </ol>
        </div>
        <div class="rel-col">
          <div class="col-title">冲突线</div>
          <ol class="rel-list">
            <li v-for="r in overview.highlights.conflicts" :key="r.id" class="conflict" @click="focusEdge(r)">
              <span class="from">{{ r.sourceName }}</span>
              <span class="rel">⚔</span>
              <span class="to">{{ r.targetName }}</span>
              <span class="weight mono">×{{ r.weight }}</span>
            </li>
            <li v-if="!overview.highlights.conflicts.length" class="empty">暂未发现明显冲突</li>
          </ol>
        </div>
        <div class="rel-col">
          <div class="col-title">三角关系</div>
          <ul class="rel-list">
            <li v-for="(t, idx) in overview.highlights.triangles" :key="idx">
              {{ t.members.map(m => m.name).join(" — ") }}
            </li>
            <li v-if="!overview.highlights.triangles.length" class="empty">暂未发现</li>
          </ul>
        </div>
        <div class="rel-col">
          <div class="col-title">孤儿警示</div>
          <ul class="rel-list">
            <li v-for="o in overview.highlights.orphans" :key="o.id" class="orphan" @click="focusNode(o.id)">
              {{ o.name }}<small> · 关联 {{ o.degree }}</small>
            </li>
            <li v-if="!overview.highlights.orphans.length" class="empty">所有角色都有戏份</li>
          </ul>
        </div>
      </div>
    </section>

    <!-- 卡片 4: Event Timeline -->
    <section v-if="overview.timeline.length" class="timeline-card workbench-card">
      <header class="card-header">
        <h3>⚡ 事件时间线</h3>
        <span class="muted">{{ overview.timeline.length }} 个事件</span>
      </header>
      <div class="timeline-rail">
        <div v-for="ev in overview.timeline" :key="ev.id" class="timeline-node" @click="focusNode(ev.id)">
          <div class="chapter mono">{{ ev.chapterId || "?" }}</div>
          <div class="dot"></div>
          <div class="ev-name">{{ ev.name }}</div>
          <div v-if="ev.participants.length" class="ev-people">{{ ev.participants.slice(0,3).map(p => p.name).join("、") }}</div>
        </div>
      </div>
    </section>

    <!-- 卡片 5: World Rules -->
    <section v-if="overview.rules.length" class="rules-card workbench-card">
      <header class="card-header">
        <h3>📜 世界规则</h3>
      </header>
      <div class="rules-grid">
        <article v-for="r in overview.rules" :key="r.id" class="rule-item" @click="focusNode(r.id)">
          <div class="rule-name">{{ r.name }}</div>
          <p v-if="r.summary" class="rule-desc">{{ r.summary }}</p>
          <div v-if="r.linked.length" class="rule-linked">
            关联：<span v-for="l in r.linked" :key="l.id" class="linked-chip">{{ l.name }}</span>
          </div>
          <div v-else class="rule-linked muted">尚未触发</div>
        </article>
      </div>
    </section>

    <!-- 卡片 7: Health Check -->
    <section v-if="overview.health.length" class="health-card workbench-card">
      <header class="card-header">
        <h3>🩺 异常与缺口</h3>
      </header>
      <div v-for="issue in overview.health" :key="issue.kind" class="health-row" :class="issue.severity">
        <div class="health-label">{{ issue.label }} · {{ issue.total }}</div>
        <div class="health-items">
          <span v-for="it in issue.items" :key="it.id" class="health-chip" @click="focusNode(it.id)">{{ it.name }}</span>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { computed } from "vue";
import { NButton } from "naive-ui";
import { buildWorldOverview } from "./worldOverviewModel.js";

const props = defineProps({
  nodes: { type: Array, default: () => [] },
  edges: { type: Array, default: () => [] },
  projectName: { type: String, default: "" },
});

const emit = defineEmits(["focus-node", "focus-edge"]);

const overview = computed(() =>
  buildWorldOverview({
    nodes: props.nodes,
    edges: props.edges,
    projectName: props.projectName,
  })
);

function focusNode(nodeId) {
  if (nodeId) emit("focus-node", nodeId);
}

function focusEdge(edge) {
  if (edge?.id) emit("focus-edge", edge);
}

function focusFirst(ids = []) {
  if (ids.length) focusNode(ids[0]);
}

function copyHook(hook) {
  const text = `${hook.title}\n\n${hook.body}\n\n涉及：${hook.involvedNames.join(" · ")}`;
  if (typeof navigator !== "undefined" && navigator.clipboard) {
    navigator.clipboard.writeText(text).catch(() => {});
  }
}
</script>

<style scoped>
.overview-dashboard {
  display: flex;
  flex-direction: column;
  gap: 14px;
  padding: 4px 2px 24px;
  overflow-y: auto;
}

.workbench-card {
  padding: 14px 18px;
  border: 1px solid var(--line-soft, #e6dcc4);
  border-radius: 10px;
  background: #fffdf7;
}

.card-header {
  display: flex;
  align-items: baseline;
  gap: 12px;
  margin-bottom: 10px;
}

.card-header h3 {
  margin: 0;
  font-size: 15px;
  color: #4a3a22;
  font-family: "ZCOOL XiaoWei", serif;
}

.muted {
  font-size: 12px;
  color: #9a8b6f;
}

.mono {
  font-family: "Courier New", monospace;
  font-size: 11px;
}

/* Hero */
.hero-card {
  background: linear-gradient(180deg, #fffaf0 0%, #fdf3df 100%);
}
.hero-title-row {
  display: flex;
  align-items: center;
  gap: 10px;
}
.hero-title {
  margin: 0;
  font-size: 22px;
  font-family: "ZCOOL XiaoWei", serif;
  color: #4a3a22;
}
.hero-badge {
  font-size: 11px;
  padding: 2px 8px;
  background: rgba(201, 138, 59, 0.18);
  color: #8a5a1e;
  border-radius: 10px;
}
.hero-stats {
  display: flex;
  gap: 22px;
  margin: 12px 0 8px;
}
.stat {
  display: flex;
  flex-direction: column;
}
.stat .num {
  font-size: 24px;
  font-weight: 600;
  color: #c98a3b;
  font-family: "Courier New", monospace;
}
.stat .lbl {
  font-size: 11px;
  color: #8a785a;
}
.hero-headline {
  margin: 6px 0;
  color: #5a4a30;
  font-size: 14px;
}
.hero-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
  margin-top: 6px;
}
.tag {
  font-size: 12px;
  padding: 2px 9px;
  border-radius: 12px;
  background: #f5ead0;
  color: #6b5a3c;
}
.tag.protagonist {
  background: rgba(201, 138, 59, 0.2);
  color: #8a5a1e;
}
.tag.org {
  background: rgba(74, 107, 58, 0.15);
  color: #4a6b3a;
}

/* Hooks */
.hooks-card {
  background: linear-gradient(180deg, #fffceb 0%, #fff8d8 100%);
}
.hooks-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 10px;
}
.hook-item {
  padding: 10px 12px;
  background: #fffefa;
  border: 1px solid rgba(201, 138, 59, 0.25);
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.hook-title {
  font-weight: 600;
  font-size: 13.5px;
  color: #4a3a22;
}
.hook-body {
  margin: 0;
  font-size: 12.5px;
  line-height: 1.5;
  color: #5a4a30;
}
.hook-meta .involved {
  font-size: 11px;
  color: #8a785a;
}
.hook-actions {
  display: flex;
  gap: 6px;
  margin-top: 4px;
}

/* Cast */
.cast-row {
  margin-bottom: 12px;
}
.row-title {
  font-size: 12px;
  color: #8a785a;
  margin-bottom: 6px;
  font-weight: 600;
}
summary.row-title {
  cursor: pointer;
}
.cast-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
  gap: 8px;
}
.cast-grid.protagonist {
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
}
.cast-grid.mini {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}
.cast-card-item {
  padding: 8px 10px;
  background: #fffaf0;
  border: 1px solid var(--line-soft, #e6dcc4);
  border-radius: 6px;
  cursor: pointer;
  transition: border-color 0.15s;
}
.cast-card-item:hover {
  border-color: #c98a3b;
}
.cast-card-item.major {
  background: linear-gradient(180deg, #fff8e6 0%, #fff2c8 100%);
}
.cast-card-item.org {
  background: #f5f8ee;
}
.cast-card-item .name {
  font-weight: 600;
  font-size: 13px;
  color: #4a3a22;
}
.cast-card-item .summary {
  margin: 3px 0;
  font-size: 11.5px;
  color: #6b5a3c;
  line-height: 1.4;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
.cast-card-item .meta {
  font-size: 10.5px;
  color: #9a8b6f;
}
.mini-chip {
  font-size: 11.5px;
  padding: 3px 8px;
  background: #f5ead0;
  border-radius: 10px;
  color: #5a4a30;
  cursor: pointer;
}
.mini-chip small {
  color: #9a8b6f;
}

/* Rel */
.rel-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 12px;
}
.col-title {
  font-size: 12px;
  font-weight: 600;
  color: #8a785a;
  margin-bottom: 4px;
}
.rel-list {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  gap: 4px;
}
.rel-list li {
  font-size: 12px;
  color: #5a4a30;
  cursor: pointer;
  display: flex;
  align-items: baseline;
  gap: 4px;
  padding: 2px 4px;
  border-radius: 4px;
}
.rel-list li:hover {
  background: rgba(201, 138, 59, 0.08);
}
.rel-list li.empty {
  color: #b3a68e;
  font-style: italic;
  cursor: default;
}
.rel-list li.empty:hover {
  background: transparent;
}
.rel-list li.conflict .rel {
  color: var(--accent-seal, #9b4326);
}
.rel-list li.orphan {
  color: #9a6b3a;
}
.rel-list .weight {
  margin-left: auto;
  color: #9a8b6f;
}
.rel-list .from,
.rel-list .to {
  font-weight: 500;
}

/* Timeline */
.timeline-rail {
  display: flex;
  gap: 6px;
  overflow-x: auto;
  padding-bottom: 8px;
}
.timeline-node {
  flex: 0 0 auto;
  min-width: 130px;
  display: flex;
  flex-direction: column;
  align-items: center;
  cursor: pointer;
  padding: 6px;
  border-radius: 6px;
}
.timeline-node:hover {
  background: rgba(201, 138, 59, 0.08);
}
.timeline-node .chapter {
  color: #9a8b6f;
}
.timeline-node .dot {
  width: 10px;
  height: 10px;
  background: #c98a3b;
  border-radius: 50%;
  margin: 4px 0;
}
.timeline-node .ev-name {
  font-size: 12px;
  font-weight: 600;
  text-align: center;
  color: #4a3a22;
}
.timeline-node .ev-people {
  font-size: 11px;
  color: #8a785a;
  text-align: center;
}

/* Rules */
.rules-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 8px;
}
.rule-item {
  padding: 8px 10px;
  background: #fffaf0;
  border: 1px solid var(--line-soft, #e6dcc4);
  border-radius: 6px;
  cursor: pointer;
}
.rule-name {
  font-weight: 600;
  font-size: 12.5px;
  color: #4a3a22;
}
.rule-desc {
  margin: 3px 0;
  font-size: 11.5px;
  color: #6b5a3c;
}
.rule-linked {
  font-size: 11px;
  color: #8a785a;
}
.linked-chip {
  display: inline-block;
  margin: 0 4px 2px 0;
  padding: 1px 6px;
  background: rgba(74, 107, 58, 0.12);
  border-radius: 8px;
  color: #4a6b3a;
}

/* Health */
.health-row {
  display: flex;
  align-items: baseline;
  gap: 10px;
  padding: 6px 0;
  border-top: 1px dashed var(--line-soft, #e6dcc4);
}
.health-row:first-of-type {
  border-top: none;
}
.health-label {
  font-size: 12px;
  font-weight: 600;
  min-width: 110px;
  color: #5a4a30;
}
.health-row.warn .health-label {
  color: var(--accent-seal, #9b4326);
}
.health-items {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}
.health-chip {
  font-size: 11px;
  padding: 1px 7px;
  background: #f5ead0;
  border-radius: 8px;
  cursor: pointer;
  color: #5a4a30;
}
.health-chip:hover {
  background: #f0dca8;
}
</style>

// frontend/src/pages/story-graph/world-overview-dashboard.tsx
import * as React from "react";
import { Copy, ExternalLink } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

import type { GraphNodeVM, GraphEdgeVM } from "./graph-view-model";
import {
  buildWorldOverview,
  type WorldOverview,
  type HighlightEdge,
} from "./world-overview-model";

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface WorldOverviewDashboardProps {
  nodes: GraphNodeVM[];
  edges: GraphEdgeVM[];
  projectName: string;
  onFocusNode?: (nodeId: string) => void;
  onFocusEdge?: (edge: HighlightEdge) => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function WorldOverviewDashboard({
  nodes,
  edges,
  projectName,
  onFocusNode,
  onFocusEdge,
}: WorldOverviewDashboardProps) {
  const overview: WorldOverview = React.useMemo(
    () => buildWorldOverview({ nodes, edges, projectName }),
    [nodes, edges, projectName],
  );

  function focusNode(nodeId: string) {
    if (nodeId) onFocusNode?.(nodeId);
  }

  function focusEdge(edge: HighlightEdge) {
    if (edge?.id) onFocusEdge?.(edge);
  }

  function focusFirst(ids: string[] = []) {
    if (ids.length) focusNode(ids[0]!);
  }

  function copyHook(hook: { title: string; body: string; involvedNames: string[] }) {
    const text = `${hook.title}\n\n${hook.body}\n\n涉及：${hook.involvedNames.join(" · ")}`;
    navigator.clipboard?.writeText(text).catch(() => {});
  }

  return (
    <div className="min-h-0 w-full space-y-3.5 overflow-y-auto overflow-x-hidden pr-1 pb-6">
      {/* Hero */}
      <Card className="border-l-4 border-l-primary bg-card p-4">
        <div className="flex flex-wrap items-center gap-2.5">
          <h2 className="min-w-0 break-words text-xl font-bold">{overview.hero.projectName}</h2>
          <span className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] text-primary">
            世界速览
          </span>
        </div>
        <div className="mt-3 flex flex-wrap gap-4">
          {[
            { num: overview.hero.totalNodes, lbl: "实体" },
            { num: overview.hero.totalEdges, lbl: "关联" },
            { num: overview.hero.typeCount, lbl: "设定类" },
            { num: overview.hero.eventCount, lbl: "事件" },
          ].map((s) => (
            <div key={s.lbl} className="flex flex-col">
              <span className="font-mono text-2xl font-semibold text-primary">{s.num}</span>
              <span className="text-[11px] text-muted-foreground">{s.lbl}</span>
            </div>
          ))}
        </div>
        <p className="mt-2 break-words text-sm">{overview.hero.headline}</p>
        {(overview.hero.protagonistNames.length > 0 || overview.hero.majorOrgNames.length > 0) && (
          <div className="mt-2 flex flex-wrap gap-1.5">
            {overview.hero.protagonistNames.map((n) => (
              <span key={`p-${n}`} className="rounded-full bg-primary/10 px-2.5 py-0.5 text-xs text-primary">
                ⭐ {n}
              </span>
            ))}
            {overview.hero.majorOrgNames.map((n) => (
              <span key={`o-${n}`} className="rounded-full bg-emerald-100 px-2.5 py-0.5 text-emerald-800 text-xs">
                ⚑ {n}
              </span>
            ))}
          </div>
        )}
      </Card>

      {/* Story Hooks */}
      {overview.hooks.length > 0 && (
        <Card className="bg-card p-3.5">
          <div className="mb-2.5 flex flex-wrap items-baseline gap-3">
            <h3 className="text-[15px] font-semibold">💡 创作锚点</h3>
            <span className="text-xs text-muted-foreground">
              基于图谱派生的可写场景种子 · 共 {overview.hooks.length} 个
            </span>
          </div>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(260px,1fr))] gap-2.5">
            {overview.hooks.map((hook, idx) => (
              <div
                key={idx}
                className="min-w-0 break-words rounded-lg border border-border bg-muted/20 p-2.5"
              >
                <div className="text-[13.5px] font-semibold">{hook.title}</div>
                <p className="text-[12.5px] leading-relaxed text-muted-foreground">{hook.body}</p>
                <div className="text-[11px] text-muted-foreground">
                  涉及：{hook.involvedNames.join(" · ")}
                </div>
                <div className="mt-1 flex flex-wrap gap-1.5">
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 px-2 text-xs"
                    onClick={() => focusFirst(hook.involvedIds)}
                  >
                    <ExternalLink className="mr-1 h-3 w-3" />
                    在图谱中查看
                  </Button>
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-6 px-2 text-xs"
                    onClick={() => copyHook(hook)}
                  >
                    <Copy className="mr-1 h-3 w-3" />
                    复制锚点
                  </Button>
                </div>
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Cast Radar */}
      <Card className="p-3.5">
        <div className="mb-2.5 flex flex-wrap items-baseline gap-3">
          <h3 className="text-[15px] font-semibold">🎭 阵容雷达</h3>
          <span className="text-xs text-muted-foreground">共 {overview.cast.totalCharacters} 个角色</span>
        </div>

        {overview.cast.protagonist.length > 0 && (
          <div className="mb-3">
            <div className="mb-1.5 text-xs font-semibold text-muted-foreground">主角</div>
            <div className="grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-2">
              {overview.cast.protagonist.map((c) => (
                <div
                  key={c.id}
                  className="min-w-0 cursor-pointer rounded-lg border bg-primary/5 p-2 transition-colors hover:border-primary"
                  onClick={() => focusNode(c.id)}
                >
                  <div className="break-words text-[13px] font-semibold">⭐ {c.name}</div>
                  {c.summary && <p className="mt-0.5 line-clamp-2 text-[11.5px] text-muted-foreground">{c.summary}</p>}
                  <div className="mt-1 font-mono text-[10.5px] text-muted-foreground">关联 {c.degree}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {overview.cast.major.length > 0 && (
          <div className="mb-3">
            <div className="mb-1.5 text-xs font-semibold text-muted-foreground">主要角色</div>
            <div className="grid grid-cols-[repeat(auto-fit,minmax(160px,1fr))] gap-2">
              {overview.cast.major.map((c) => (
                <div
                  key={c.id}
                  className="min-w-0 cursor-pointer rounded-lg border bg-card p-2 transition-colors hover:border-primary"
                  onClick={() => focusNode(c.id)}
                >
                  <div className="break-words text-[13px] font-semibold">{c.name}</div>
                  {c.summary && <p className="mt-0.5 line-clamp-2 text-[11.5px] text-muted-foreground">{c.summary}</p>}
                  <div className="mt-1 font-mono text-[10.5px] text-muted-foreground">关联 {c.degree}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {(overview.cast.supporting.length > 0 || overview.cast.minor.length > 0) && (
          <details className="mb-3">
            <summary className="cursor-pointer text-xs font-semibold text-muted-foreground">
              辅助 / 次要角色（{overview.cast.supporting.length + overview.cast.minor.length}）
            </summary>
            <div className="mt-1.5 flex flex-wrap gap-1.5">
              {[...overview.cast.supporting, ...overview.cast.minor].map((c) => (
                <span
                  key={c.id}
                  className="cursor-pointer rounded-full bg-muted px-2 py-0.5 text-[11.5px] hover:bg-muted/80"
                  onClick={() => focusNode(c.id)}
                >
                  {c.name}<small className="text-muted-foreground"> · {c.degree}</small>
                </span>
              ))}
            </div>
          </details>
        )}

        {overview.cast.organizations.length > 0 && (
          <div>
            <div className="mb-1.5 text-xs font-semibold text-muted-foreground">组织 / 势力</div>
            <div className="grid grid-cols-[repeat(auto-fit,minmax(160px,1fr))] gap-2">
              {overview.cast.organizations.map((o) => (
                <div
                  key={o.id}
                  className="min-w-0 cursor-pointer rounded-lg border bg-emerald-50/70 p-2 transition-colors hover:border-emerald-500"
                  onClick={() => focusNode(o.id)}
                >
                  <div className="break-words text-[13px] font-semibold">⚑ {o.name}</div>
                  {o.summary && <p className="mt-0.5 line-clamp-2 text-[11.5px] text-muted-foreground">{o.summary}</p>}
                  <div className="mt-1 font-mono text-[10.5px] text-muted-foreground">关联 {o.degree}</div>
                </div>
              ))}
            </div>
          </div>
        )}
      </Card>

      {/* Relationship Highlights */}
      <Card className="p-3.5">
        <h3 className="mb-2.5 text-[15px] font-semibold">💞 关系亮点</h3>
        <div className="grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-3">
          <div>
            <div className="mb-1 text-xs font-semibold text-muted-foreground">核心羁绊 Top 5</div>
            <ol className="m-0 flex list-none flex-col gap-1 p-0">
              {overview.highlights.topBonds.length > 0 ? overview.highlights.topBonds.map((r) => (
                <li
                  key={r.id}
                  className="flex min-w-0 flex-wrap items-baseline gap-1 rounded px-1 py-0.5 text-xs hover:bg-muted/40"
                  onClick={() => focusEdge(r)}
                >
                  <span className="font-medium">{r.sourceName}</span>
                  <span className="text-muted-foreground">— {r.label} →</span>
                  <span className="font-medium">{r.targetName}</span>
                  <span className="ml-auto font-mono text-muted-foreground">×{r.weight}</span>
                </li>
              )) : (
                <li className="text-xs italic text-muted-foreground">暂无</li>
              )}
            </ol>
          </div>
          <div>
            <div className="mb-1 text-xs font-semibold text-muted-foreground">冲突线</div>
            <ol className="m-0 flex list-none flex-col gap-1 p-0">
              {overview.highlights.conflicts.length > 0 ? overview.highlights.conflicts.map((r) => (
                <li
                  key={r.id}
                  className="flex min-w-0 flex-wrap items-baseline gap-1 rounded px-1 py-0.5 text-xs hover:bg-muted/40"
                  onClick={() => focusEdge(r)}
                >
                  <span className="font-medium">{r.sourceName}</span>
                  <span className="text-red-600">⚔</span>
                  <span className="font-medium">{r.targetName}</span>
                  <span className="ml-auto font-mono text-muted-foreground">×{r.weight}</span>
                </li>
              )) : (
                <li className="text-xs italic text-muted-foreground">暂未发现明显冲突</li>
              )}
            </ol>
          </div>
          <div>
            <div className="mb-1 text-xs font-semibold text-muted-foreground">三角关系</div>
            <ul className="m-0 flex list-none flex-col gap-1 p-0">
              {overview.highlights.triangles.length > 0 ? overview.highlights.triangles.map((t, idx) => (
                <li key={idx} className="text-xs">
                  {t.members.map((m) => m.name).join(" — ")}
                </li>
              )) : (
                <li className="text-xs italic text-muted-foreground">暂未发现</li>
              )}
            </ul>
          </div>
          <div>
            <div className="mb-1 text-xs font-semibold text-muted-foreground">孤儿警示</div>
            <ul className="m-0 flex list-none flex-col gap-1 p-0">
              {overview.highlights.orphans.length > 0 ? overview.highlights.orphans.map((o) => (
                <li
                  key={o.id}
                  className="cursor-pointer text-xs text-amber-700 hover:underline"
                  onClick={() => focusNode(o.id)}
                >
                  {o.name}<small className="text-muted-foreground"> · 关联 {o.degree}</small>
                </li>
              )) : (
                <li className="text-xs italic text-muted-foreground">所有角色都有戏份</li>
              )}
            </ul>
          </div>
        </div>
      </Card>

      {/* Event Timeline */}
      {overview.timeline.length > 0 && (
        <Card className="p-3.5">
          <div className="mb-2.5 flex flex-wrap items-baseline gap-3">
            <h3 className="text-[15px] font-semibold">⚡ 事件时间线</h3>
            <span className="text-xs text-muted-foreground">{overview.timeline.length} 个事件</span>
          </div>
          <div className="flex gap-1.5 overflow-x-auto pb-2">
            {overview.timeline.map((ev) => (
              <div
                key={ev.id}
                className="flex min-w-[130px] shrink-0 cursor-pointer flex-col items-center rounded-lg p-1.5 hover:bg-muted/30"
                onClick={() => focusNode(ev.id)}
              >
                <div className="font-mono text-[11px] text-muted-foreground">{ev.chapterId || "?"}</div>
                <div className="my-1 h-2.5 w-2.5 rounded-full bg-amber-500" />
                <div className="break-words text-center text-xs font-semibold">{ev.name}</div>
                {ev.participants.length > 0 && (
                  <div className="mt-0.5 text-center text-[11px] text-muted-foreground">
                    {ev.participants.slice(0, 3).map((p) => p.name).join("、")}
                  </div>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* World Rules */}
      {overview.rules.length > 0 && (
        <Card className="p-3.5">
          <h3 className="mb-2.5 text-[15px] font-semibold">📜 世界规则</h3>
          <div className="grid grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-2">
            {overview.rules.map((r) => (
              <div
                key={r.id}
                className="min-w-0 cursor-pointer rounded-lg border p-2 hover:border-primary"
                onClick={() => focusNode(r.id)}
              >
                <div className="break-words text-[12.5px] font-semibold">{r.name}</div>
                {r.summary && <p className="mt-0.5 text-[11.5px] text-muted-foreground">{r.summary}</p>}
                {r.linked.length > 0 ? (
                  <div className="mt-1 text-[11px] text-muted-foreground">
                    关联：
                    {r.linked.map((l) => (
                      <span
                        key={l.id}
                        className="mr-1 inline-block rounded-full bg-green-100 px-1.5 py-0.5 text-green-800"
                      >
                        {l.name}
                      </span>
                    ))}
                  </div>
                ) : (
                  <div className="mt-1 text-[11px] text-muted-foreground">尚未触发</div>
                )}
              </div>
            ))}
          </div>
        </Card>
      )}

      {/* Health Check */}
      {overview.health.length > 0 && (
        <Card className="p-3.5">
          <h3 className="mb-2.5 text-[15px] font-semibold">🩺 异常与缺口</h3>
          {overview.health.map((issue) => (
            <div
              key={issue.kind}
              className={cn(
                "flex items-baseline gap-2.5 border-t border-dashed border-border/60 py-1.5 first:border-t-0",
                issue.severity === "warn" && "text-red-700",
              )}
            >
              <div className="min-w-[110px] text-xs font-semibold">
                {issue.label} · {issue.total}
              </div>
              <div className="flex flex-wrap gap-1">
                {issue.items.map((it) => (
                  <span
                    key={it.id}
                    className="cursor-pointer rounded-full bg-muted px-2 py-0.5 text-[11px] hover:bg-muted/70"
                    onClick={() => focusNode(it.id)}
                  >
                    {it.name}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </Card>
      )}
    </div>
  );
}
