// frontend/src/pages/story-graph/agent-template-configurator.tsx
import * as React from "react";
import { Loader2 } from "lucide-react";

import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";

import {
  formatArchiveKindLabel,
  formatArchiveSectionLabel,
  formatArchiveTierLabel,
  sectionKeysByTier,
  tierSelectOptions,
} from "./archive-template-labels";
import { sanitizeDisplayText } from "./display-text";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

export interface ArchiveCandidate {
  entity_uuid: string;
  display_name: string;
  summary: string;
  agent_kind: string;
  recommended_importance_tier: string;
  selected_importance_tier?: string;
  template_sections?: string[];
  [key: string]: unknown;
}

interface AgentTemplateConfiguratorProps {
  open: boolean;
  candidates: ArchiveCandidate[];
  busy: boolean;
  error: string;
  onClose: () => void;
  onConfirm: (candidateSnapshot: ArchiveCandidate[]) => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function AgentTemplateConfigurator({
  open,
  candidates,
  busy,
  error,
  onClose,
  onConfirm,
}: AgentTemplateConfiguratorProps) {
  const [tierState, setTierState] = React.useState<Record<string, string>>({});

  React.useEffect(() => {
    const initial: Record<string, string> = {};
    for (const item of candidates) {
      initial[item.entity_uuid] =
        item.selected_importance_tier || item.recommended_importance_tier || "supporting";
    }
    setTierState(initial);
  }, [candidates]);

  function resolvedTier(entityUuid: string): string {
    return tierState[entityUuid] || "supporting";
  }

  function updateTier(entityUuid: string, value: string) {
    setTierState((prev) => ({ ...prev, [entityUuid]: value }));
  }

  function previewSections(item: ArchiveCandidate): string[] {
    return sectionKeysByTier[resolvedTier(item.entity_uuid)] || item.template_sections || [];
  }

  function handleConfirm() {
    onConfirm(
      candidates.map((item) => ({
        ...item,
        selected_importance_tier: resolvedTier(item.entity_uuid),
      })),
    );
  }

  const groupedCandidates = React.useMemo(() => {
    const groups = new Map<string, { kind: string; label: string; items: ArchiveCandidate[] }>();
    for (const item of candidates) {
      const kind = item.agent_kind || "generic";
      if (!groups.has(kind)) {
        groups.set(kind, { kind, label: formatArchiveKindLabel(kind), items: [] });
      }
      groups.get(kind)!.items.push(item);
    }
    return Array.from(groups.values());
  }, [candidates]);

  return (
    <Dialog open={open} onOpenChange={(o) => { if (!o) onClose(); }}>
      <DialogContent className="sm:max-w-[900px]">
        <DialogHeader>
          <DialogTitle>档案模板确认</DialogTitle>
          <DialogDescription>
            系统已按叙事重要度推荐档位，你只需调整少量对象。
          </DialogDescription>
        </DialogHeader>

        {error ? (
          <p className="text-sm text-destructive">{error}</p>
        ) : (
          <ScrollArea className="max-h-[60vh]">
            <div className="flex flex-col gap-3 pr-2">
              {groupedCandidates.map((group) => (
                <div key={group.kind} className="flex flex-col gap-2.5">
                  <div className="text-sm font-bold">
                    {group.label} · {group.items.length}
                  </div>
                  {group.items.map((item) => (
                    <div
                      key={item.entity_uuid}
                      className="flex min-w-0 flex-col gap-1.5 rounded-lg border p-3"
                    >
                      <div className="flex items-start justify-between gap-3">
                        <div className="min-w-0">
                          <strong className="break-words text-sm">
                            {sanitizeDisplayText(item.display_name, { emptyLabel: "未命名对象" })}
                          </strong>
                          <div className="font-mono text-[11px] text-muted-foreground">
                            推荐 {formatArchiveTierLabel(item.recommended_importance_tier)} ·{" "}
                            当前 {formatArchiveTierLabel(resolvedTier(item.entity_uuid))}
                          </div>
                        </div>
                        <Select
                          value={resolvedTier(item.entity_uuid)}
                          onValueChange={(val) => updateTier(item.entity_uuid, val ?? "supporting")}
                        >
                          <SelectTrigger className="w-[130px]">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {tierSelectOptions.map((opt) => (
                              <SelectItem key={opt.value} value={opt.value}>
                                {opt.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>
                      <p className="break-words text-xs text-muted-foreground">
                        {sanitizeDisplayText(item.summary, { emptyLabel: "" })}
                      </p>
                      <div className="flex flex-wrap gap-1">
                        {previewSections(item).map((section) => (
                          <Badge key={section} variant="secondary" className="text-[10px]">
                            {formatArchiveSectionLabel(section)}
                          </Badge>
                        ))}
                      </div>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          </ScrollArea>
        )}

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            取消
          </Button>
          <Button disabled={busy} onClick={handleConfirm}>
            {busy && <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />}
            确认并生成档案
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

// frontend/src/views/story-graph/AgentTemplateConfigurator.vue
<template>
  <div v-if="visible" class="configurator-backdrop" @click.self="$emit('close')">
    <article class="configurator-panel workbench-card">
      <header class="configurator-header">
        <div>
          <h3 class="title-ancient">档案模板确认</h3>
          <p class="subtitle">系统已按叙事重要度推荐档位，你只需调整少量对象。</p>
        </div>
        <button class="btn" type="button" @click="$emit('close')">关闭</button>
      </header>

      <p v-if="error" class="status-box error">{{ error }}</p>
      <div v-else class="configurator-groups">
        <section v-for="group in groupedCandidates" :key="group.kind" class="candidate-group">
          <div class="group-title">{{ group.label }} · {{ group.items.length }}</div>
          <div v-for="item in group.items" :key="item.entity_uuid" class="candidate-card">
            <div class="candidate-head">
              <div>
                <strong>{{ item.display_name }}</strong>
                <div class="candidate-meta mono">
                  推荐 {{ formatArchiveTierLabel(item.recommended_importance_tier) }} · 当前 {{ formatArchiveTierLabel(resolvedTier(item.entity_uuid)) }}
                </div>
              </div>
              <select :value="resolvedTier(item.entity_uuid)" @change="updateTier(item.entity_uuid, $event.target.value)">
                <option v-for="option in tierSelectOptions" :key="option.value" :value="option.value">
                  {{ option.label }}
                </option>
              </select>
            </div>
            <p class="candidate-summary">{{ item.summary }}</p>
            <div class="candidate-sections">
              <span v-for="section in previewSections(item)" :key="section" class="section-chip">
                {{ formatArchiveSectionLabel(section) }}
              </span>
            </div>
          </div>
        </section>
      </div>

      <footer class="configurator-footer">
        <button class="btn" type="button" @click="$emit('close')">取消</button>
        <button class="btn primary" type="button" :disabled="busy" @click="confirm">
          {{ busy ? "生成中..." : "确认并生成档案" }}
        </button>
      </footer>
    </article>
  </div>
</template>

<script setup>
import { computed, reactive, watch } from "vue";
import {
  formatArchiveKindLabel,
  formatArchiveSectionLabel,
  formatArchiveTierLabel,
  sectionKeysByTier,
  tierSelectOptions,
} from "./archiveTemplateLabels.js";

const props = defineProps({
  visible: { type: Boolean, default: false },
  candidates: { type: Array, default: () => [] },
  busy: { type: Boolean, default: false },
  error: { type: String, default: "" },
});

const emit = defineEmits(["close", "confirm"]);

const tierState = reactive({});

watch(
  () => props.candidates,
  (candidates) => {
    Object.keys(tierState).forEach((key) => { delete tierState[key]; });
    for (const item of candidates) {
      tierState[item.entity_uuid] = item.selected_importance_tier || item.recommended_importance_tier || "supporting";
    }
  },
  { immediate: true },
);

const groupedCandidates = computed(() => {
  const groups = new Map();
  for (const item of props.candidates) {
    const kind = item.agent_kind || "generic";
    if (!groups.has(kind)) {
      groups.set(kind, { kind, label: formatArchiveKindLabel(kind), items: [] });
    }
    groups.get(kind).items.push(item);
  }
  return Array.from(groups.values());
});

function resolvedTier(entityUuid) {
  return tierState[entityUuid] || "supporting";
}

function updateTier(entityUuid, value) {
  tierState[entityUuid] = value;
}

function previewSections(item) {
  return sectionKeysByTier[resolvedTier(item.entity_uuid)] || item.template_sections || [];
}

function confirm() {
  emit("confirm", props.candidates.map((item) => ({
    ...item,
    selected_importance_tier: resolvedTier(item.entity_uuid),
  })));
}
</script>

<style scoped>
.configurator-backdrop {
  position: fixed;
  inset: 0;
  background: rgba(41, 30, 18, 0.56);
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 24px;
  z-index: 40;
}

.configurator-panel {
  width: min(920px, 100%);
  max-height: min(88vh, 920px);
  overflow: auto;
  padding: 18px;
}

.configurator-header,
.candidate-head,
.configurator-footer {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  align-items: flex-start;
}

.configurator-groups,
.candidate-group,
.candidate-card {
  display: grid;
  gap: 10px;
}

.configurator-groups {
  margin-top: 14px;
}

.candidate-card {
  padding: 12px;
  border: 1px solid var(--line-soft);
  border-radius: 12px;
  background: #fffaf1;
}

.candidate-meta,
.candidate-summary,
.subtitle {
  color: var(--text-sub);
}

.candidate-sections {
  display: flex;
  flex-wrap: wrap;
  gap: 6px;
}

.section-chip {
  padding: 4px 8px;
  border-radius: 999px;
  background: #f5ead4;
  color: var(--text-main);
  font-size: 12px;
}

.group-title {
  font-weight: 700;
}

.configurator-footer {
  margin-top: 16px;
}

.status-box.error {
  color: #9b4326;
}
</style>
