// frontend/src/pages/story-graph/graph-build-console.tsx
import * as React from "react";
import { AlertTriangle, ChevronDown, RotateCcw } from "lucide-react";

import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

import {
  BUILD_STAGE_ORDER,
  describeStage,
  formatCounts,
  formatElapsed,
} from "./build-stage-meta";
import { formatStageSampleLabel, sanitizeDisplayText } from "./display-text";
import type { TaskData, StageEvent } from "./graph-build-task-poller";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface GraphBuildConsoleProps {
  task: TaskData | null;
  onRetry: () => void;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function GraphBuildConsole({ task, onRetry }: GraphBuildConsoleProps) {
  const [showTrace, setShowTrace] = React.useState(false);

  const stages: StageEvent[] = React.useMemo(() => {
    const meta = task?.metadata || {};
    return Array.isArray(meta.stages) ? meta.stages : [];
  }, [task]);

  const failedEvent = React.useMemo(
    () => [...stages].reverse().find((e) => e.stage === "failed") || null,
    [stages],
  );

  const hasFailed = failedEvent !== null || task?.status === "failed";

  const lastSuccessfulStage = React.useMemo(() => {
    const list = stages.filter((e) => e.stage !== "failed");
    return list.length ? list[list.length - 1]! : null;
  }, [stages]);

  const currentStage = lastSuccessfulStage;

  const currentMeta = describeStage(currentStage?.stage || "");

  const currentCountsLabel = formatCounts(currentStage?.counts || {});

  const currentSampleLabels = React.useMemo(() => {
    const sample = currentStage?.sample || [];
    return (sample as unknown[])
      .map(formatStageSampleLabel)
      .filter(Boolean)
      .slice(0, 3);
  }, [currentStage]);

  const progressValue = React.useMemo(() => {
    if (hasFailed) return Math.min(100, currentStage?.progress || 0);
    if (task?.status === "completed") return 100;
    return Math.max(0, Math.min(100, currentStage?.progress || task?.progress || 0));
  }, [hasFailed, task, currentStage]);

  const totalElapsedLabel = React.useMemo(() => {
    const last = stages.length ? stages[stages.length - 1]! : null;
    return formatElapsed(last?.elapsed_ms || 0);
  }, [stages]);

  const headIcon = hasFailed ? "⚠" : task?.status === "completed" ? "✅" : "⚙";
  const headTitle = hasFailed
    ? "图谱构建中断"
    : task?.status === "completed"
      ? "图谱构建完成"
      : "图谱构建中…";
  const headSub = currentStage
    ? `当前阶段：${describeStage(currentStage.stage).title}`
    : "正在准备…";

  const failedAfterLabel = React.useMemo(() => {
    const after = failedEvent?.failed_after || lastSuccessfulStage?.stage || "";
    return describeStage(after).title;
  }, [failedEvent, lastSuccessfulStage]);

  const failedSummary = React.useMemo(
    () => sanitizeDisplayText(failedEvent?.error_summary || "构建失败", { emptyLabel: "构建失败" }),
    [failedEvent],
  );

  const timelineEntries = React.useMemo(() => {
    const eventByStage: Record<string, StageEvent> = {};
    for (const evt of stages) {
      if (evt.stage === "failed") continue;
      eventByStage[evt.stage] = evt;
    }
    const currentKey = currentStage?.stage || "";
    let reachedCurrent = false;
    return BUILD_STAGE_ORDER.map((key) => {
      const meta = describeStage(key);
      const evt = eventByStage[key];
      let statusClass: string;
      let dot: string;
      if (evt) {
        const isCurrent = key === currentKey && !((evt.progress || 0) >= 100);
        if (isCurrent) {
          statusClass = "text-amber-600 font-semibold animate-pulse";
          dot = "▶";
          reachedCurrent = true;
        } else {
          statusClass = "text-green-700";
          dot = "✓";
        }
      } else if (!reachedCurrent && hasFailed && failedEvent?.failed_after === key) {
        statusClass = "text-red-700 font-semibold";
        dot = "✕";
      } else {
        statusClass = "text-muted-foreground";
        dot = "○";
      }
      return {
        key,
        title: meta.title,
        dot,
        statusClass,
        meta: evt
          ? `${formatElapsed(evt.elapsed_ms || 0)}　${formatCounts(evt.counts || {})}`
          : "—",
      };
    });
  }, [stages, currentStage, hasFailed, failedEvent]);

  return (
    <Card
      className={cn(
        "flex flex-col gap-2.5 p-3.5",
        hasFailed && "border-red-300 bg-red-50/40",
      )}
    >
      {/* Header */}
      <div className="flex items-center justify-between gap-3">
        <div className="flex items-center gap-2.5">
          <span className="text-xl">{headIcon}</span>
          <div>
            <div className="text-[15px] font-semibold">{headTitle}</div>
            <div className="text-xs text-muted-foreground">{headSub}</div>
          </div>
        </div>
        <div className="flex gap-3 font-mono text-xs text-muted-foreground">
          <span>已用时 {totalElapsedLabel}</span>
          <span>{progressValue}%</span>
        </div>
      </div>

      {/* Progress bar */}
      <div className="relative h-1.5 overflow-hidden rounded-full bg-muted">
        <div
          className="absolute inset-y-0 left-0 bg-gradient-to-r from-amber-500 to-amber-400 transition-all duration-400"
          style={{ width: `${progressValue}%` }}
        />
      </div>

      {/* Current stage detail */}
      {currentStage && (
        <div className="flex flex-col gap-1 rounded-lg border border-dashed border-amber-300/60 bg-amber-50/30 p-2.5">
          <div className="flex items-baseline gap-2">
            <span className="text-base">{currentMeta.icon}</span>
            <span className="font-semibold">{currentMeta.title}</span>
            <span className="ml-auto font-mono text-[11px] text-muted-foreground">
              {currentCountsLabel}
            </span>
          </div>
          {currentMeta.description && (
            <div className="text-xs text-muted-foreground">{currentMeta.description}</div>
          )}
          {currentSampleLabels.length > 0 && (
            <div className="flex flex-wrap items-center gap-1.5 text-xs">
              <span className="text-muted-foreground">示例：</span>
              {currentSampleLabels.map((item, idx) => (
                <span
                  key={idx}
                  className="rounded-full bg-amber-100/60 px-2 py-0.5 text-amber-800"
                >
                  {item}
                </span>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Stage timeline grid */}
      <ol className="m-0 grid list-none grid-cols-[repeat(auto-fit,minmax(220px,1fr))] gap-x-3 gap-y-1 p-0">
        {timelineEntries.map((entry) => (
          <li key={entry.key} className={cn("flex items-baseline gap-1.5 text-xs", entry.statusClass)}>
            <span className="w-3.5 text-center">{entry.dot}</span>
            <span className="shrink-0">{entry.title}</span>
            <span className="ml-auto font-mono text-[11px] opacity-80">{entry.meta}</span>
          </li>
        ))}
      </ol>

      {/* Failure box */}
      {hasFailed && (
        <div className="flex flex-col gap-2 rounded-lg border border-red-200 bg-white p-2.5">
          <div className="flex items-center gap-1.5 text-[13px] text-red-700">
            <AlertTriangle className="h-3.5 w-3.5" />
            出错于「{failedAfterLabel}」：{failedSummary}
          </div>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" onClick={() => setShowTrace(!showTrace)}>
              <ChevronDown className={cn("mr-1 h-3 w-3 transition-transform", showTrace && "rotate-180")} />
              {showTrace ? "收起技术详情" : "展开技术详情"}
            </Button>
            <Button size="sm" onClick={onRetry}>
              <RotateCcw className="mr-1 h-3 w-3" />
              重试构建
            </Button>
          </div>
          {showTrace && (
            <pre className="max-h-[200px] overflow-auto whitespace-pre-wrap rounded bg-muted/40 p-2 font-mono text-[11px]">
              {failedEvent?.traceback || ""}
            </pre>
          )}
        </div>
      )}
    </Card>
  );
}

// frontend/src/views/story-graph/GraphBuildConsole.vue
<template>
  <section class="build-console workbench-card" :class="{ failed: hasFailed }">
    <header class="console-head">
      <div class="head-main">
        <span class="head-icon">{{ headIcon }}</span>
        <div>
          <div class="head-title">{{ headTitle }}</div>
          <div class="head-sub">{{ headSub }}</div>
        </div>
      </div>
      <div class="head-meta mono">
        <span>已用时 {{ totalElapsedLabel }}</span>
        <span>{{ progressValue }}%</span>
      </div>
    </header>

    <div class="progress-track">
      <div class="progress-fill" :style="{ width: progressValue + '%' }"></div>
    </div>

    <div v-if="currentStage" class="current-stage">
      <div class="stage-headline">
        <span class="stage-icon">{{ currentMeta.icon }}</span>
        <span class="stage-title">{{ currentMeta.title }}</span>
        <span class="stage-counts mono">{{ currentCountsLabel }}</span>
      </div>
      <div v-if="currentMeta.description" class="stage-desc">{{ currentMeta.description }}</div>
      <div v-if="currentSampleLabels.length" class="stage-samples">
        <span class="sample-prefix">示例：</span>
        <span v-for="(item, idx) in currentSampleLabels" :key="idx" class="sample-chip">{{ item }}</span>
      </div>
    </div>

    <ol class="stage-timeline">
      <li
        v-for="entry in timelineEntries"
        :key="entry.key"
        class="timeline-item"
        :class="entry.statusClass"
      >
        <span class="dot">{{ entry.dot }}</span>
        <span class="title">{{ entry.title }}</span>
        <span class="meta mono">{{ entry.meta }}</span>
      </li>
    </ol>

    <div v-if="hasFailed" class="failure-box">
      <div class="failure-summary">
        ⚠ 出错于「{{ failedAfterLabel }}」：{{ failedEvent.error_summary || "构建失败" }}
      </div>
      <div class="failure-actions">
        <n-button size="small" @click="showTrace = !showTrace">
          {{ showTrace ? "收起堆栈" : "展开堆栈" }}
        </n-button>
        <n-button size="small" type="primary" @click="$emit('retry')">重试构建</n-button>
      </div>
      <pre v-if="showTrace" class="trace mono">{{ failedEvent.traceback || "" }}</pre>
    </div>
  </section>
</template>

<script setup>
import { computed, ref } from "vue";
import { NButton } from "naive-ui";
import {
  BUILD_STAGE_ORDER,
  describeStage,
  formatCounts,
  formatElapsed,
} from "./buildStageMeta.js";

const props = defineProps({
  task: { type: Object, default: () => null },
});

defineEmits(["retry"]);

const showTrace = ref(false);

const stages = computed(() => {
  const meta = props.task?.metadata || {};
  return Array.isArray(meta.stages) ? meta.stages : [];
});

const failedEvent = computed(
  () => stages.value.slice().reverse().find((e) => e.stage === "failed") || null
);

const hasFailed = computed(
  () => failedEvent.value !== null || props.task?.status === "failed"
);

const lastSuccessfulStage = computed(() => {
  const list = stages.value.filter((e) => e.stage !== "failed");
  return list.length ? list[list.length - 1] : null;
});

const currentStage = computed(() => lastSuccessfulStage.value);

const currentMeta = computed(() =>
  describeStage(currentStage.value?.stage || "")
);

const currentCountsLabel = computed(() =>
  formatCounts(currentStage.value?.counts || {})
);

const currentSampleLabels = computed(() => {
  const sample = currentStage.value?.sample || [];
  return sample
    .map((item) => {
      if (item == null) return "";
      if (typeof item === "string") return item;
      if (typeof item === "object") {
        if (item.name) {
          const aliases = Array.isArray(item.aliases) && item.aliases.length
            ? `（${item.aliases.join("、")}）`
            : "";
          return `${item.name}${aliases}`;
        }
        if (item.fact) return item.fact;
      }
      return String(item);
    })
    .filter(Boolean)
    .slice(0, 3);
});

const progressValue = computed(() => {
  if (hasFailed.value) {
    return Math.min(100, currentStage.value?.progress || 0);
  }
  if (props.task?.status === "completed") return 100;
  return Math.max(0, Math.min(100, currentStage.value?.progress || props.task?.progress || 0));
});

const totalElapsedLabel = computed(() => {
  const last = stages.value.length ? stages.value[stages.value.length - 1] : null;
  return formatElapsed(last?.elapsed_ms || 0);
});

const headIcon = computed(() => {
  if (hasFailed.value) return "⚠";
  if (props.task?.status === "completed") return "✅";
  return "⚙";
});

const headTitle = computed(() => {
  if (hasFailed.value) return "图谱构建中断";
  if (props.task?.status === "completed") return "图谱构建完成";
  return "图谱构建中…";
});

const headSub = computed(() => {
  if (currentStage.value) {
    return `当前阶段：${describeStage(currentStage.value.stage).title}`;
  }
  return "正在准备…";
});

const failedAfterLabel = computed(() => {
  const after = failedEvent.value?.failed_after || lastSuccessfulStage.value?.stage || "";
  return describeStage(after).title;
});

const timelineEntries = computed(() => {
  const eventByStage = {};
  for (const evt of stages.value) {
    if (evt.stage === "failed") continue;
    eventByStage[evt.stage] = evt;
  }
  const currentKey = currentStage.value?.stage || "";
  let reachedCurrent = false;
  return BUILD_STAGE_ORDER.map((key) => {
    const meta = describeStage(key);
    const evt = eventByStage[key];
    let statusClass;
    let dot;
    if (evt) {
      const isCurrent = key === currentKey && !(evt.progress >= 100);
      if (isCurrent) {
        statusClass = "stage-current";
        dot = "▶";
        reachedCurrent = true;
      } else {
        statusClass = "stage-done";
        dot = "✓";
      }
    } else if (!reachedCurrent && hasFailed.value && failedEvent.value?.failed_after === key) {
      statusClass = "stage-failed";
      dot = "✕";
    } else {
      statusClass = "stage-pending";
      dot = "◯";
    }
    return {
      key,
      title: meta.title,
      dot,
      statusClass,
      meta: evt
        ? `${formatElapsed(evt.elapsed_ms || 0)}　${formatCounts(evt.counts || {})}`
        : "—",
    };
  });
});
</script>

<style scoped>
.build-console {
  display: flex;
  flex-direction: column;
  gap: 10px;
  padding: 14px 18px;
  border: 1px solid var(--line-soft);
  border-radius: 10px;
  background: linear-gradient(180deg, #fffaf2 0%, #fdf6e7 100%);
}

.build-console.failed {
  background: linear-gradient(180deg, #fff7f4 0%, #ffeae3 100%);
  border-color: rgba(155, 67, 38, 0.4);
}

.console-head {
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
}

.head-main {
  display: flex;
  align-items: center;
  gap: 10px;
}

.head-icon {
  font-size: 22px;
}

.head-title {
  font-size: 15px;
  font-weight: 600;
  color: #4a3a22;
}

.head-sub {
  font-size: 12px;
  color: #8a785a;
}

.head-meta {
  display: flex;
  gap: 12px;
  font-size: 12px;
  color: #6b5a3c;
}

.progress-track {
  position: relative;
  height: 6px;
  background: rgba(120, 90, 50, 0.12);
  border-radius: 3px;
  overflow: hidden;
}

.progress-fill {
  position: absolute;
  top: 0;
  left: 0;
  bottom: 0;
  background: linear-gradient(90deg, #c98a3b, #e0a857);
  transition: width 0.4s ease;
}

.current-stage {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 8px 10px;
  background: #fffdf6;
  border: 1px dashed rgba(184, 138, 71, 0.4);
  border-radius: 6px;
}

.stage-headline {
  display: flex;
  align-items: baseline;
  gap: 8px;
}

.stage-icon {
  font-size: 16px;
}

.stage-title {
  font-weight: 600;
  color: #4a3a22;
}

.stage-counts {
  margin-left: auto;
  font-size: 11.5px;
  color: #8a785a;
}

.stage-desc {
  font-size: 12px;
  color: #6b5a3c;
}

.stage-samples {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 6px;
  font-size: 12px;
  color: #5a4a30;
}

.sample-prefix {
  color: #9a8b6f;
}

.sample-chip {
  padding: 1px 8px;
  background: rgba(201, 138, 59, 0.12);
  border-radius: 10px;
}

.stage-timeline {
  list-style: none;
  margin: 0;
  padding: 0;
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 4px 12px;
}

.timeline-item {
  display: flex;
  align-items: baseline;
  gap: 6px;
  font-size: 12px;
  padding: 2px 0;
  color: #8a785a;
}

.timeline-item .dot {
  width: 14px;
  text-align: center;
}

.timeline-item.stage-done {
  color: #4a6b3a;
}

.timeline-item.stage-current {
  color: #c98a3b;
  font-weight: 600;
  animation: pulse-current 1.6s infinite;
}

.timeline-item.stage-failed {
  color: var(--accent-seal, #9b4326);
  font-weight: 600;
}

.timeline-item .title {
  flex-shrink: 0;
}

.timeline-item .meta {
  margin-left: auto;
  font-size: 11px;
  opacity: 0.85;
}

@keyframes pulse-current {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.55; }
}

.failure-box {
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 10px;
  background: #fff;
  border: 1px solid rgba(155, 67, 38, 0.3);
  border-radius: 6px;
}

.failure-summary {
  font-size: 13px;
  color: var(--accent-seal, #9b4326);
}

.failure-actions {
  display: flex;
  gap: 8px;
}

.trace {
  max-height: 200px;
  overflow: auto;
  font-size: 11px;
  background: #fcf6ec;
  padding: 8px;
  border-radius: 4px;
  white-space: pre-wrap;
  color: #564a36;
}

.mono {
  font-family: "Courier New", monospace;
}
</style>
