// frontend/src/views/character-console/AgentDetailPanel.vue
<template>
  <article class="workbench-card panel detail-panel">
    <h2 class="card-title">对象详情</h2>
    <p>展示当前对象的结构化档案字段，直接来自 worldline agent state。</p>

    <div v-if="!selectedAgent" class="empty">选择对象后，这里会显示身份、动机、关系与行动倾向。</div>
    <div v-else class="detail-sections">
      <section class="detail-block" v-for="item in detailSections" :key="item.key">
        <div class="detail-title">{{ item.label }}</div>

        <p v-if="item.variant === 'text'" class="detail-text">{{ item.text }}</p>

        <dl v-else-if="item.variant === 'entries'" class="detail-entries">
          <div
            v-for="entry in item.entries"
            :key="`${item.key}-${entry.label}`"
            class="detail-entry"
          >
            <dt>{{ entry.label }}</dt>
            <dd>{{ entry.value }}</dd>
          </div>
        </dl>

        <ul v-else class="detail-items">
          <li v-for="entry in item.items" :key="`${item.key}-${entry}`">
            {{ entry }}
          </li>
        </ul>
      </section>
    </div>
  </article>
</template>

<script setup>
import { computed } from "vue";

import { buildSelectedAgentDetailSections } from "./agentDetailPresentation.js";

const props = defineProps({
  selectedAgent: { type: Object, default: null },
});

const detailSections = computed(() => buildSelectedAgentDetailSections(props.selectedAgent));
</script>

<style scoped>
.panel {
  padding: 16px;
}

.panel p {
  color: var(--text-sub);
}

.detail-sections {
  display: grid;
  gap: 10px;
  margin-top: 10px;
}

.detail-block {
  display: grid;
  gap: 8px;
  border: 1px solid var(--line-soft);
  border-radius: 12px;
  padding: 12px;
  background: #fffaf1;
}

.detail-title {
  font-weight: 700;
  color: var(--accent-copper-deep);
}

.detail-text,
.detail-entry dd,
.detail-items li {
  margin: 0;
  color: var(--text-main);
  white-space: pre-wrap;
  line-height: 1.7;
}

.detail-entries {
  display: grid;
  gap: 8px;
  margin: 0;
}

.detail-entry {
  display: grid;
  gap: 4px;
}

.detail-entry dt {
  color: var(--text-dim);
  font-size: 12px;
}

.detail-items {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.detail-items li {
  padding: 4px 10px;
  border-radius: 999px;
  background: rgba(176, 125, 75, 0.12);
  color: var(--accent-copper-deep);
  font-size: 13px;
}
</style>

// frontend/src/pages/character-console/agent-detail-panel.tsx
import * as React from "react";

import { cn } from "@/lib/utils";
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

import {
  buildSelectedAgentDetailSections,
  type AgentData,
  type DetailSection,
} from "./agent-detail-presentation";

/* ------------------------------------------------------------------ */
/*  Props                                                              */
/* ------------------------------------------------------------------ */

interface AgentDetailPanelProps {
  selectedAgent: AgentData | null;
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function AgentDetailPanel({ selectedAgent }: AgentDetailPanelProps) {
  const detailSections = React.useMemo(
    () => buildSelectedAgentDetailSections(selectedAgent),
    [selectedAgent],
  );

  return (
    <Card className="flex flex-col gap-2 p-2.5">
      <h2 className="text-sm font-semibold">对象详情</h2>
      <p className="text-xs text-muted-foreground">
        展示当前对象的结构化档案字段，直接来自 worldline agent state。
      </p>

      {!selectedAgent ? (
        <div className="flex min-h-[120px] items-center justify-center text-xs text-muted-foreground">
          选择对象后，这里会显示身份、动机、关系与行动倾向。
        </div>
      ) : (
        <ScrollArea className="max-h-[calc(100vh-500px)] min-h-0">
          <div className="flex flex-col gap-2">
            {detailSections.map((section) => (
              <div
                key={section.key}
                className="rounded-lg border bg-muted/20 p-2.5"
              >
                <div className="text-xs font-bold text-primary">
                  {section.label}
                </div>

                {section.variant === "text" && (
                  <p className="mt-1 whitespace-pre-wrap text-sm leading-relaxed">
                    {section.text}
                  </p>
                )}

                {section.variant === "entries" && (
                  <dl className="mt-1 flex flex-col gap-1.5">
                    {section.entries?.map((entry) => (
                      <div key={entry.label} className="flex flex-col gap-0.5">
                        <dt className="text-[11px] text-muted-foreground">{entry.label}</dt>
                        <dd className="text-sm leading-relaxed">{entry.value}</dd>
                      </div>
                    ))}
                  </dl>
                )}

                {section.variant === "items" && (
                  <div className="mt-1 flex flex-wrap gap-1.5">
                    {section.items?.map((item) => (
                      <span
                        key={item}
                        className="rounded-full bg-primary/8 px-2.5 py-0.5 text-[13px] text-primary"
                      >
                        {item}
                      </span>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>
        </ScrollArea>
      )}
    </Card>
  );
}
