// frontend/src/views/character-console/InteractionLogPanel.vue
<template>
  <article class="workbench-card panel">
    <h2 class="card-title">交互日志</h2>
    <div class="logs">
      <div v-for="(item, idx) in logs" :key="idx" class="log-item">
        <div class="mono">{{ item.time }}</div>
        <div>{{ item.text }}</div>
      </div>
      <div v-if="!logs.length" class="empty">暂无日志，执行第一条动作后会记录在这里。</div>
    </div>
  </article>
</template>

<script setup>
defineProps({
  logs: { type: Array, default: () => [] },
});
</script>

<style scoped>
.panel {
  padding: 16px;
}

.logs {
  margin-top: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
  max-height: 460px;
  overflow: auto;
}

.log-item {
  border: 1px solid var(--line-soft);
  border-radius: 10px;
  padding: 10px;
  background: #fffbf3;
  display: grid;
  gap: 5px;
}
</style>

// frontend/src/pages/character-console/interaction-log-panel.tsx
import * as React from "react";

import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface LogEntry {
  time: string;
  text: string;
}

interface InteractionLogPanelProps {
  logs: LogEntry[];
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function InteractionLogPanel({ logs }: InteractionLogPanelProps) {
  return (
    <Card className="flex flex-col gap-2 p-2.5">
      <h2 className="text-sm font-semibold">交互日志</h2>

      <ScrollArea className="max-h-[460px]">
        {logs.length === 0 ? (
          <p className="py-4 text-center text-xs text-muted-foreground">
            暂无日志，执行第一条动作后会记录在这里。
          </p>
        ) : (
          <div className="flex flex-col gap-2">
            {logs.map((item, idx) => (
              <div
                key={idx}
                className="rounded-lg border bg-muted/20 p-2"
              >
                <div className="font-mono text-[10px] text-muted-foreground">
                  {item.time}
                </div>
                <div className="text-xs">{item.text}</div>
              </div>
            ))}
          </div>
        )}
      </ScrollArea>
    </Card>
  );
}
