// frontend/src/pages/character-console/agent-dialogue-panel.tsx
import * as React from "react";
import { Send, Loader2 } from "lucide-react";

import { cn } from "@/lib/utils";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { Textarea } from "@/components/ui/textarea";

import type { AgentData } from "./agent-detail-presentation";

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

interface ChatReply {
  reply?: string;
  generator_mode?: string;
  model_name?: string;
  suggested_actions?: string[];
  [key: string]: unknown;
}

interface DialogueItem {
  dialogue_id: string;
  generator_mode: string;
  message: string;
  reply: string;
  created_at?: string;
}

interface AgentDialoguePanelProps {
  sessionId: string;
  selectedAgent: AgentData | null;
  chatMode: string;
  chatMessage: string;
  chatReply: ChatReply | null;
  dialogues: DialogueItem[];
  chatError: string;
  busy: boolean;
  onUpdateChatMode: (value: string) => void;
  onUpdateChatMessage: (value: string) => void;
  onSubmit: () => void;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function formatTime(value: unknown): string {
  if (!value) return "--";
  const date = new Date(String(value));
  return Number.isNaN(date.getTime()) ? String(value) : date.toLocaleString("zh-CN", { hour12: false });
}

const CHAT_MODE_OPTIONS = [
  { label: "template", value: "template" },
  { label: "llm", value: "llm" },
] as const;

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export function AgentDialoguePanel({
  sessionId,
  selectedAgent,
  chatMode,
  chatMessage,
  chatReply,
  dialogues,
  chatError,
  busy,
  onUpdateChatMode,
  onUpdateChatMessage,
  onSubmit,
}: AgentDialoguePanelProps) {
  return (
    <Card className="flex flex-col gap-2.5 p-2.5">
      <h2 className="text-sm font-semibold">对象对话入口</h2>
      <p className="text-xs text-muted-foreground">
        从右侧对象名册选中一个对象后，直接向它发送一句话并查看回应。
      </p>

      <div className="grid gap-2.5 md:grid-cols-3">
        {/* Current agent */}
        <div className="flex flex-col gap-1">
          <label className="text-xs font-medium text-muted-foreground">当前对话对象</label>
          <div className="rounded-lg border px-3 py-2 text-sm">
            {selectedAgent?.display_name || "请先从右侧点选对象"}
          </div>
        </div>

        {/* Mode selector */}
        <div className="flex flex-col gap-1">
          <label className="text-xs font-medium text-muted-foreground">生成模式</label>
          <Select value={chatMode} onValueChange={(v) => onUpdateChatMode(v ?? "template")}>
            <SelectTrigger>
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {CHAT_MODE_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Message input */}
        <div className="flex flex-col gap-1">
          <label className="text-xs font-medium text-muted-foreground">你要说的话</label>
          <Textarea
            value={chatMessage}
            onChange={(e) => onUpdateChatMessage(e.target.value)}
            placeholder="例如：你是否愿意在今晚之前公开证据？"
            className="min-h-[50px] text-sm"
          />
        </div>
      </div>

      <Button
        disabled={busy || !sessionId || !selectedAgent}
        onClick={onSubmit}
        className="self-start"
      >
        {busy ? (
          <Loader2 className="mr-1.5 h-3.5 w-3.5 animate-spin" />
        ) : (
          <Send className="mr-1.5 h-3.5 w-3.5" />
        )}
        发送对话
      </Button>

      {/* Chat reply */}
      {chatReply && (
        <div className="rounded-lg border p-2.5">
          <div className="text-xs font-bold">对象回复</div>
          <p className="mt-1 text-sm">{chatReply.reply || "暂无回复文本"}</p>
          <Separator className="my-1.5" />
          <div className="text-xs font-bold">生成信息</div>
          <div className="font-mono text-[11px] text-muted-foreground">
            {chatReply.generator_mode || chatMode} · {chatReply.model_name || "无模型"}
          </div>
          {chatReply.suggested_actions && chatReply.suggested_actions.length > 0 && (
            <>
              <Separator className="my-1.5" />
              <div className="text-xs font-bold">建议动作</div>
              {chatReply.suggested_actions.map((item, idx) => (
                <div key={idx} className="border-t border-dashed border-border/40 py-1 text-xs">
                  {idx + 1}. {item}
                </div>
              ))}
            </>
          )}
        </div>
      )}

      {/* Dialogue history */}
      {dialogues.length > 0 && (
        <div className="rounded-lg border p-2.5">
          <div className="text-xs font-bold">最近对话历史</div>
          {dialogues.map((item) => (
            <div
              key={item.dialogue_id}
              className="border-t border-dashed border-border/40 py-1.5"
            >
              <div className="font-mono text-[10px] text-muted-foreground">
                {item.generator_mode} · {formatTime(item.created_at)}
              </div>
              <div className="text-xs">Q: {item.message}</div>
              <div className="text-xs">A: {item.reply}</div>
            </div>
          ))}
        </div>
      )}

      {chatError && (
        <Badge variant="destructive" className="self-start">{chatError}</Badge>
      )}
    </Card>
  );
}

// frontend/src/views/character-console/AgentDialoguePanel.vue
<template>
  <article class="workbench-card panel full">
    <h2 class="card-title">对象对话入口</h2>
    <p>从右侧对象名册选中一个对象后，直接向它发送一句话并查看回应。</p>

    <div class="chat-grid">
      <div class="field">
        <label>当前对话对象</label>
        <div class="chat-chip">{{ selectedAgent?.display_name || "请先从右侧点选对象" }}</div>
      </div>
      <div class="field">
        <label>生成模式</label>
        <select :value="chatMode" @change="emitMode($event.target.value)">
          <option value="template">template</option>
          <option value="llm">llm</option>
        </select>
      </div>
      <div class="field">
        <label>你要说的话</label>
        <textarea :value="chatMessage" placeholder="例如：你是否愿意在今晚之前公开证据？" @input="emitUpdate($event.target.value)"></textarea>
      </div>
    </div>

    <div class="toolbar-row">
      <button class="btn primary" :disabled="busy || !sessionId || !selectedAgent" @click="$emit('submit')">发送对话</button>
    </div>

    <div v-if="chatReply" class="chat-reply">
      <div class="seed-title">对象回复</div>
      <p>{{ chatReply.reply || "暂无回复文本" }}</p>
      <div class="seed-title">生成信息</div>
      <div class="mono">{{ chatReply.generator_mode || chatMode }} · {{ chatReply.model_name || "无模型" }}</div>
      <div class="seed-title">建议动作</div>
      <div class="suggestion-item" v-for="(item, idx) in chatReply.suggested_actions || []" :key="`chat_action_${idx}`">
        {{ idx + 1 }}. {{ item }}
      </div>
    </div>
    <div class="chat-reply" v-if="dialogues.length">
      <div class="seed-title">最近对话历史</div>
      <div class="suggestion-item" v-for="item in dialogues" :key="item.dialogue_id">
        <div class="mono">{{ item.generator_mode }} · {{ formatTime(item.created_at) }}</div>
        <div>Q: {{ item.message }}</div>
        <div>A: {{ item.reply }}</div>
      </div>
    </div>
    <p class="status-text error" v-if="chatError">{{ chatError }}</p>
  </article>
</template>

<script setup>
defineProps({
  sessionId: { type: String, default: "" },
  selectedAgent: { type: Object, default: null },
  chatMode: { type: String, default: "template" },
  chatMessage: { type: String, default: "" },
  chatReply: { type: Object, default: null },
  dialogues: { type: Array, default: () => [] },
  chatError: { type: String, default: "" },
  busy: { type: Boolean, default: false },
});

const emit = defineEmits(["update:chatMessage", "update:chatMode", "submit"]);

function emitUpdate(value) {
  emit("update:chatMessage", value);
}

function emitMode(value) {
  emit("update:chatMode", value);
}

function formatTime(value) {
  if (!value) {
    return "--";
  }
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? value : date.toLocaleString("zh-CN", { hour12: false });
}
</script>

<style scoped>
.full {
  grid-column: 1 / -1;
}

.panel {
  padding: 16px;
}

.panel p {
  color: var(--text-sub);
}

.chat-grid {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: 10px;
}

.chat-reply,
.chat-chip {
  border: 1px solid var(--line-soft);
  border-radius: 12px;
  background: #fffaf1;
}

.chat-reply {
  margin-top: 12px;
  padding: 12px;
}

.chat-chip {
  padding: 10px 12px;
}

select {
  width: 100%;
  border: 1px solid var(--line-soft);
  border-radius: 10px;
  padding: 8px 10px;
  background: #fffaf1;
}

.seed-title {
  font-weight: 700;
  margin: 8px 0 5px;
}

.seed-title:first-child {
  margin-top: 0;
}

.suggestion-item {
  border-top: 1px dashed var(--line-soft);
  padding: 7px 0;
}

.suggestion-item:first-of-type {
  border-top: none;
}

.status-text.error {
  color: #9b4326;
}

@media (max-width: 1200px) {
  .chat-grid {
    grid-template-columns: 1fr;
  }
}
</style>
