// frontend/src/views/overview/SeedTaskStageCard.vue
<template>
  <section class="log-card stage-card">
    <div class="stage-top">
      <div>
        <div class="section-code mono">当前阶段</div>
        <h3>{{ activeStage.label || "等待上传" }}</h3>
      </div>
      <span class="stage-status mono" :class="statusClass">{{ statusText }}</span>
    </div>
    <div class="stage-metrics">
      <div class="metric-box">
        <span class="metric-label mono">进度</span>
        <strong>{{ stageProgress.percent }}%</strong>
      </div>
      <div class="metric-box">
        <span class="metric-label mono">耗时</span>
        <strong>{{ elapsedText }}</strong>
      </div>
      <div class="metric-box">
        <span class="metric-label mono">{{ workMetricLabel }}</span>
        <strong>{{ workMetricValue }}</strong>
      </div>
      <div class="metric-box">
        <span class="metric-label mono">章节数</span>
        <strong>{{ chapterSummary }}</strong>
      </div>
    </div>
    <div class="stage-track">
      <div class="stage-bar" :style="{ width: `${stageProgress.percent}%` }"></div>
    </div>
  </section>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from "vue";

import { deriveStageProgress, formatElapsedDuration } from "./seedUploadTaskView";
import { formatTaskStageStatus } from "../../utils/chineseDisplay";

const props = defineProps({
  activeStage: { type: Object, required: true },
  taskStatus: { type: String, default: "" },
  taskMetrics: { type: Object, required: true },
  timeline: { type: Array, default: () => [] },
  startedAt: { type: String, default: "" },
});

const now = ref(Date.now());
let timerId = 0;

const resolvedStatus = computed(() => {
  if (props.activeStage.status === "failed" || props.taskStatus === "failed") return "failed";
  if (props.activeStage.status === "completed" || props.taskStatus === "completed") return "completed";
  if (props.activeStage.status === "processing" || props.taskStatus === "processing") return "processing";
  return "pending";
});
const statusText = computed(() => formatTaskStageStatus(resolvedStatus.value));
const statusClass = computed(() => {
  if (resolvedStatus.value === "processing") return "running";
  if (resolvedStatus.value === "completed") return "done";
  return resolvedStatus.value;
});
const stageProgress = computed(() =>
  deriveStageProgress(props.activeStage, props.taskMetrics, props.timeline),
);
const elapsedText = computed(() => formatElapsedDuration(props.startedAt, now.value));
const blockSummary = computed(() => {
  if (!props.taskMetrics.totalBlocks) return "-";
  return `${props.taskMetrics.completedBlocks}/${props.taskMetrics.totalBlocks}`;
});
const chapterSummary = computed(() => (props.taskMetrics.chapterCount ? String(props.taskMetrics.chapterCount) : "-"));
const workMetricLabel = computed(() => {
  if (props.activeStage.key === "sequential_reading") return "阅读段";
  return "分析块";
});
const workMetricValue = computed(() => {
  if (props.activeStage.key === "sequential_reading") {
    return stageProgress.value.detail;
  }
  return blockSummary.value;
});

onMounted(() => {
  timerId = window.setInterval(() => {
    now.value = Date.now();
  }, 1000);
});

onBeforeUnmount(() => {
  window.clearInterval(timerId);
});
</script>

<style scoped>
.log-card {
  border: 1px solid var(--line-soft);
  border-radius: 16px;
  background: linear-gradient(180deg, rgba(255, 251, 242, 0.98), rgba(255, 247, 233, 0.98));
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.7);
  padding: 14px;
}

.stage-top,
.stage-metrics {
  display: flex;
  gap: 10px;
}

.stage-top {
  align-items: flex-start;
  justify-content: space-between;
}

.stage-top h3 {
  margin: 4px 0 0;
  font-size: 20px;
  font-family: "ZCOOL XiaoWei", serif;
}

.section-code,
.metric-label {
  font-size: 11px;
  letter-spacing: 0.08em;
  color: var(--text-sub);
}

.stage-status {
  border-radius: 999px;
  padding: 5px 10px;
  font-size: 11px;
}

.stage-status.running {
  background: rgba(143, 79, 31, 0.12);
  color: var(--accent-copper);
}

.stage-status.done {
  background: rgba(56, 106, 79, 0.14);
  color: var(--accent-green);
}

.stage-status.failed {
  background: rgba(155, 67, 38, 0.14);
  color: #9b4326;
}

.stage-status.pending {
  background: rgba(39, 90, 120, 0.1);
  color: var(--accent-blue);
}

.stage-metrics {
  margin-top: 14px;
  flex-wrap: wrap;
}

.metric-box {
  min-width: 120px;
  flex: 1 1 120px;
  border: 1px solid rgba(159, 141, 106, 0.35);
  border-radius: 12px;
  background: rgba(255, 252, 245, 0.8);
  padding: 10px 12px;
}

.metric-box strong {
  display: block;
  margin-top: 6px;
  font-size: 18px;
}

.stage-track {
  margin-top: 14px;
  height: 9px;
  border-radius: 999px;
  overflow: hidden;
  background: #eddcbd;
}

.stage-bar {
  height: 100%;
  border-radius: inherit;
  background: linear-gradient(90deg, #9a5824 0%, #d2a25e 58%, #ebd7b0 100%);
  transition: width 180ms ease;
}
</style>

// frontend/src/pages/overview/seed-task-stage-card.tsx
/**
 * SeedTaskStageCard — shows current active stage with progress bar and metrics.
 */

import { useEffect, useState } from "react";

import { cn } from "@/lib/utils";
import type { ActiveStage, TaskMetrics, TimelineEvent } from "@/lib/seed-upload-task-state";
import {
  deriveStageProgress,
  formatElapsedDuration,
} from "@/lib/seed-upload-task-view";

/* ---------- Display helpers ---------- */

const TASK_STAGE_STATUS_TEXT: Record<string, string> = {
  processing: "进行中",
  completed: "已完成",
  failed: "失败",
  pending: "待开始",
  active: "进行中",
};

function formatTaskStageStatus(value: string): string {
  return TASK_STAGE_STATUS_TEXT[value] || "待开始";
}

/* ---------- Props ---------- */

interface SeedTaskStageCardProps {
  activeStage: ActiveStage;
  taskStatus: string;
  taskMetrics: TaskMetrics;
  timeline: TimelineEvent[];
  startedAt: string;
}

/* ---------- Component ---------- */

export default function SeedTaskStageCard({
  activeStage,
  taskStatus,
  taskMetrics,
  timeline,
  startedAt,
}: SeedTaskStageCardProps) {
  const [now, setNow] = useState(Date.now());

  useEffect(() => {
    const id = window.setInterval(() => setNow(Date.now()), 1000);
    return () => window.clearInterval(id);
  }, []);

  const resolvedStatus = (() => {
    if (activeStage.status === "failed" || taskStatus === "failed") return "failed";
    if (activeStage.status === "completed" || taskStatus === "completed")
      return "completed";
    if (activeStage.status === "processing" || taskStatus === "processing")
      return "processing";
    return "pending";
  })();

  const statusText = formatTaskStageStatus(resolvedStatus);
  const stageProgress = deriveStageProgress(activeStage, taskMetrics, timeline);
  const elapsedText = formatElapsedDuration(startedAt, now);

  const blockSummary = taskMetrics.totalBlocks
    ? `${taskMetrics.completedBlocks}/${taskMetrics.totalBlocks}`
    : "-";
  const chapterSummary = taskMetrics.chapterCount
    ? String(taskMetrics.chapterCount)
    : "-";

  const workMetricLabel =
    activeStage.key === "sequential_reading" ? "阅读段" : "分析块";
  const workMetricValue =
    activeStage.key === "sequential_reading"
      ? stageProgress.detail
      : blockSummary;

  const statusColor: Record<string, string> = {
    processing: "bg-amber-100/70 text-amber-700",
    completed: "bg-emerald-100/70 text-emerald-700",
    failed: "bg-red-100/70 text-red-700",
    pending: "bg-blue-100/70 text-blue-700",
  };

  return (
    <section className="rounded-xl border p-3.5 bg-gradient-to-b from-amber-50/80 to-amber-50/40 shadow-sm space-y-3.5">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div>
          <div className="font-mono text-[11px] tracking-wide text-muted-foreground">
            当前阶段
          </div>
          <h3 className="mt-1 font-serif text-xl font-semibold">
            {activeStage.label || "等待上传"}
          </h3>
        </div>
        <span
          className={cn(
            "rounded-full px-2.5 py-1 text-[11px] font-mono",
            statusColor[resolvedStatus] || statusColor.pending,
          )}
        >
          {statusText}
        </span>
      </div>

      {/* Metric boxes */}
      <div className="flex flex-wrap gap-2.5 mt-3">
        {[
          { label: "进度", value: `${stageProgress.percent}%` },
          { label: "耗时", value: elapsedText },
          { label: workMetricLabel, value: workMetricValue },
          { label: "章节数", value: chapterSummary },
        ].map((m) => (
          <div
            key={m.label}
            className="flex-1 min-w-[7.5rem] rounded-xl border bg-amber-50/50 p-2.5"
          >
            <span className="block font-mono text-[11px] tracking-wide text-muted-foreground">
              {m.label}
            </span>
            <strong className="block mt-1.5 text-lg text-foreground">
              {m.value}
            </strong>
          </div>
        ))}
      </div>

      {/* Progress bar */}
      <div className="mt-3 h-2 rounded-full overflow-hidden bg-amber-100">
        <div
          className="h-full rounded-full bg-gradient-to-r from-amber-700 via-amber-500 to-amber-200 transition-[width] duration-200"
          style={{ width: `${stageProgress.percent}%` }}
        />
      </div>
    </section>
  );
}
