// frontend/src/views/overview/SeedTaskTimeline.vue
<template>
  <section class="log-card timeline-card">
    <div class="timeline-head">
      <div>
        <div class="section-code mono">时间轴卷宗</div>
        <h3>{{ title }}</h3>
      </div>
      <span class="timeline-hint">{{ hintText }}</span>
    </div>
    <div ref="scrollRef" class="timeline-list" @scroll="handleScroll">
      <article v-for="event in events" :key="event.id" class="timeline-item" :class="event.status">
        <div class="timeline-rail">
          <span class="timeline-dot"></span>
        </div>
        <div class="timeline-body">
          <div class="timeline-top">
            <strong>{{ event.title }}</strong>
            <span class="mono">{{ formatTimelineTimestamp(event.timestamp) }}</span>
          </div>
          <p v-if="event.detail" class="timeline-detail">{{ event.detail }}</p>
          <div class="chip-row">
            <span class="chip mono">{{ formatStageKey(event.stage) }}</span>
            <span v-for="chip in buildEventChips(event)" :key="`${event.id}_${chip}`" class="chip mono">{{ chip }}</span>
          </div>
        </div>
      </article>
    </div>
  </section>
</template>

<script setup>
import { nextTick, ref, watch } from "vue";

import { buildEventChips, formatTimelineTimestamp } from "./seedUploadTaskView";
import { formatStageKey } from "../../utils/chineseDisplay";

const props = defineProps({
  events: { type: Array, required: true },
  title: { type: String, default: "阶段日志" },
  hintText: { type: String, default: "自动追踪最新事件" },
});

const scrollRef = ref(null);
const autoStick = ref(true);

watch(
  () => props.events.length,
  async () => {
    await nextTick();
    if (autoStick.value) {
      scrollToBottom();
    }
  },
  { immediate: true },
);

function handleScroll() {
  const node = scrollRef.value;
  if (!node) return;
  const distance = node.scrollHeight - node.scrollTop - node.clientHeight;
  autoStick.value = distance < 40;
}

function scrollToBottom() {
  const node = scrollRef.value;
  if (!node) return;
  node.scrollTop = node.scrollHeight;
}
</script>

<style scoped>
.log-card {
  border: 1px solid var(--line-soft);
  border-radius: 16px;
  background: linear-gradient(180deg, rgba(255, 252, 246, 0.98), rgba(248, 242, 229, 0.98));
  padding: 14px;
}

.timeline-head,
.timeline-top,
.chip-row {
  display: flex;
  gap: 8px;
}

.timeline-head {
  align-items: flex-start;
  justify-content: space-between;
}

.timeline-head h3 {
  margin: 4px 0 0;
  font-size: 18px;
  font-family: "ZCOOL XiaoWei", serif;
}

.section-code,
.timeline-hint {
  color: var(--text-sub);
}

.section-code {
  font-size: 11px;
  letter-spacing: 0.08em;
}

.timeline-hint {
  font-size: 12px;
}

.timeline-list {
  margin-top: 14px;
  max-height: 420px;
  overflow: auto;
  padding-right: 4px;
}

.timeline-item {
  display: grid;
  grid-template-columns: 18px minmax(0, 1fr);
  gap: 12px;
}

.timeline-item + .timeline-item {
  margin-top: 14px;
}

.timeline-rail {
  position: relative;
}

.timeline-rail::after {
  content: "";
  position: absolute;
  left: 8px;
  top: 8px;
  bottom: -22px;
  width: 1px;
  background: rgba(159, 141, 106, 0.45);
}

.timeline-item:last-child .timeline-rail::after {
  display: none;
}

.timeline-dot {
  position: relative;
  z-index: 1;
  display: block;
  width: 16px;
  height: 16px;
  border-radius: 999px;
  border: 2px solid rgba(159, 141, 106, 0.55);
  background: #fff7e9;
}

.timeline-body {
  border: 1px solid rgba(159, 141, 106, 0.28);
  border-radius: 14px;
  background: rgba(255, 251, 243, 0.86);
  padding: 12px;
}

.timeline-item.active .timeline-body {
  border-color: rgba(143, 79, 31, 0.42);
  box-shadow: 0 10px 24px rgba(143, 79, 31, 0.08);
}

.timeline-item.failed .timeline-body {
  border-color: rgba(155, 67, 38, 0.42);
}

.timeline-item.completed {
  opacity: 0.9;
}

.timeline-detail {
  margin: 8px 0 0;
  color: var(--text-sub);
}

.chip-row {
  flex-wrap: wrap;
  margin-top: 10px;
}

.chip {
  border: 1px solid rgba(159, 141, 106, 0.34);
  border-radius: 999px;
  padding: 4px 9px;
  font-size: 11px;
  background: rgba(255, 255, 255, 0.6);
}

@media (max-width: 768px) {
  .timeline-list {
    max-height: 320px;
  }
}
</style>

// frontend/src/pages/overview/seed-task-timeline.tsx
/**
 * SeedTaskTimeline — vertical timeline of processing stage events.
 */

import { useCallback, useEffect, useRef, useState } from "react";

import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import type { TimelineEvent } from "@/lib/seed-upload-task-state";
import {
  buildEventChips,
  formatTimelineTimestamp,
} from "@/lib/seed-upload-task-view";

/* ---------- Display helpers ---------- */

const STAGE_KEY_TEXT: Record<string, string> = {
  queued: "等待开始",
  extract_text: "提取上传文本",
  smart_segmentation: "智能分段",
  sequential_reading: "顺序深度阅读",
  arc_summary: "弧线摘要",
  global_integration: "全局整合",
  ontology: "梳理故事结构",
  agent_profiles: "角色Agent档案",
  completed: "全部完成",
  failed: "执行失败",
  uploading: "文件上传",
};

function formatStageKey(key: string): string {
  return STAGE_KEY_TEXT[key] || key;
}

/* ---------- Props ---------- */

interface SeedTaskTimelineProps {
  events: TimelineEvent[];
  title?: string;
  hintText?: string;
}

/* ---------- Component ---------- */

export default function SeedTaskTimeline({
  events,
  title = "阶段日志",
  hintText = "自动追踪最新事件",
}: SeedTaskTimelineProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [autoStick, setAutoStick] = useState(true);

  const scrollToBottom = useCallback(() => {
    const node = scrollRef.current;
    if (node) node.scrollTop = node.scrollHeight;
  }, []);

  useEffect(() => {
    if (autoStick) scrollToBottom();
  }, [events.length, autoStick, scrollToBottom]);

  const handleScroll = useCallback(() => {
    const node = scrollRef.current;
    if (!node) return;
    const distance = node.scrollHeight - node.scrollTop - node.clientHeight;
    setAutoStick(distance < 40);
  }, []);

  return (
    <section className="rounded-xl border p-2.5 bg-gradient-to-b from-amber-50/80 to-amber-50/40 space-y-2.5">
      {/* Header */}
      <div className="flex items-start justify-between gap-2">
        <div>
          <div className="font-mono text-[11px] tracking-wide text-muted-foreground">
            时间轴卷宗
          </div>
          <h3 className="mt-1 font-serif text-base font-semibold">{title}</h3>
        </div>
        <span className="text-xs text-muted-foreground">{hintText}</span>
      </div>

      {/* Events list */}
      <div
        ref={scrollRef}
        className="mt-2.5 max-h-[420px] overflow-auto pr-1 space-y-2.5"
        onScroll={handleScroll}
      >
        {events.map((event, idx) => {
          const chips = buildEventChips(event);
          return (
            <article
              key={event.id}
              className="grid gap-2"
              style={{ gridTemplateColumns: "18px minmax(0,1fr)" }}
            >
              {/* Rail */}
              <div className="relative">
                <span
                  className={cn(
                    "relative z-[1] block w-4 h-4 rounded-full border-2",
                    event.status === "active"
                      ? "border-amber-500 bg-amber-100"
                      : event.status === "failed"
                        ? "border-red-500 bg-red-100"
                        : "border-muted-foreground/40 bg-amber-50",
                  )}
                />
                {idx < events.length - 1 && (
                  <div className="absolute left-[7px] top-4 bottom-[-18px] w-px bg-muted-foreground/30" />
                )}
              </div>

              {/* Body */}
              <div
                className={cn(
                  "rounded-lg border p-2.5",
                  event.status === "active"
                    ? "border-amber-500/40 bg-amber-50/80 shadow-md"
                    : event.status === "failed"
                      ? "border-red-500/40 bg-red-50/80"
                      : event.status === "completed"
                        ? "border-border bg-amber-50/60 opacity-90"
                        : "border-border bg-amber-50/60",
                )}
              >
                <div className="flex items-center justify-between gap-2">
                  <strong className="text-sm">{event.title}</strong>
                  <span className="font-mono text-[11px] text-muted-foreground">
                    {formatTimelineTimestamp(event.timestamp)}
                  </span>
                </div>
                {event.detail && (
                  <p className="mt-2 text-sm text-muted-foreground">
                    {event.detail}
                  </p>
                )}
                <div className="flex flex-wrap gap-1.5 mt-2.5">
                  <Badge variant="secondary" className="text-[11px]">
                    {formatStageKey(event.stage)}
                  </Badge>
                  {chips.map((chip) => (
                    <Badge
                      key={`${event.id}_${chip}`}
                      variant="secondary"
                      className="text-[11px]"
                    >
                      {chip}
                    </Badge>
                  ))}
                </div>
              </div>
            </article>
          );
        })}
      </div>
    </section>
  );
}
